linters-settings:
  govet:
    check-shadowing: true

linters:
  enable-all: true
  # enable:
  #   - gofmt
  #   - staticcheck
  #   - gosec
  #   - gosimple
  #   - govet
  #   - ineffassign

run:
  issues-exit-code: 1