//go:build  !purego

// Copyright 2020-2024 Consensys Software Inc.
// Licensed under the Apache License, Version 2.0. See the LICENSE file for details.

// Code generated by consensys/gnark-crypto DO NOT EDIT

// We include the hash to force the Go compiler to recompile: 8339322716531241176
#include "../asm/element_31b_arm64.s"

