// Copyright 2020 ConsenSys Software Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by consensys/gnark-crypto DO NOT EDIT

package integration

// /!\ WARNING /!\
// this code has not been audited and is provided as-is. In particular,
// there is no security guarantees such as constant time implementation
// or side-channel attack resistance
// /!\ WARNING /!\

import (
	"crypto/rand"
	"encoding/binary"
	"errors"
	"io"
	"math/big"
	"math/bits"
	"reflect"
	"strconv"
	"sync"
)

// e_nocarry_0632 represents a field element stored on 10 words (uint64)
// e_nocarry_0632 are assumed to be in Montgomery form in all methods
// field modulus q =
//
// 15997330371119326030998758261187590592261285703225304540790896233282253032166432468548839712631130797331408317396474928106086789176888948343661180579234590234513192787040215804651070123247977
type e_nocarry_0632 [10]uint64

// Limbs number of 64 bits words needed to represent e_nocarry_0632
const Limbs = 10

// Bits number bits needed to represent e_nocarry_0632
const Bits = 632

// Bytes number bytes needed to represent e_nocarry_0632
const Bytes = Limbs * 8

// field modulus stored as big.Int
var _modulus big.Int

// Modulus returns q as a big.Int
// q =
//
// 15997330371119326030998758261187590592261285703225304540790896233282253032166432468548839712631130797331408317396474928106086789176888948343661180579234590234513192787040215804651070123247977
func Modulus() *big.Int {
	return new(big.Int).Set(&_modulus)
}

// q (modulus)
var qe_nocarry_0632 = e_nocarry_0632{
	816069973256538473,
	6387843321064356065,
	14536823245358974728,
	3528214618953670924,
	7206257926599825404,
	5159858282989125618,
	4277310149175820203,
	2252378430875190398,
	2933629967605268401,
	64680000015521443,
}

// rSquare
var rSquare = e_nocarry_0632{
	14095748637358075099,
	14972327332075549804,
	7361626879976866655,
	11832497490297147285,
	12761415501496589237,
	6643493509961268799,
	16277603966381323758,
	4172976593577508314,
	11557828093366462360,
	35540955938236791,
}

var bigIntPool = sync.Pool{
	New: func() interface{} {
		return new(big.Int)
	},
}

func init() {
	_modulus.SetString("15997330371119326030998758261187590592261285703225304540790896233282253032166432468548839712631130797331408317396474928106086789176888948343661180579234590234513192787040215804651070123247977", 10)
}

// SetUint64 z = v, sets z LSB to v (non-Montgomery form) and convert z to Montgomery form
func (z *e_nocarry_0632) SetUint64(v uint64) *e_nocarry_0632 {
	*z = e_nocarry_0632{v}
	return z.Mul(z, &rSquare) // z.ToMont()
}

// Set z = x
func (z *e_nocarry_0632) Set(x *e_nocarry_0632) *e_nocarry_0632 {
	z[0] = x[0]
	z[1] = x[1]
	z[2] = x[2]
	z[3] = x[3]
	z[4] = x[4]
	z[5] = x[5]
	z[6] = x[6]
	z[7] = x[7]
	z[8] = x[8]
	z[9] = x[9]
	return z
}

// SetInterface converts provided interface into e_nocarry_0632
// returns an error if provided type is not supported
// supported types: e_nocarry_0632, *e_nocarry_0632, uint64, int, string (interpreted as base10 integer),
// *big.Int, big.Int, []byte
func (z *e_nocarry_0632) SetInterface(i1 interface{}) (*e_nocarry_0632, error) {
	switch c1 := i1.(type) {
	case e_nocarry_0632:
		return z.Set(&c1), nil
	case *e_nocarry_0632:
		return z.Set(c1), nil
	case uint64:
		return z.SetUint64(c1), nil
	case int:
		return z.SetString(strconv.Itoa(c1)), nil
	case string:
		return z.SetString(c1), nil
	case *big.Int:
		return z.SetBigInt(c1), nil
	case big.Int:
		return z.SetBigInt(&c1), nil
	case []byte:
		return z.SetBytes(c1), nil
	default:
		return nil, errors.New("can't set integration.e_nocarry_0632 from type " + reflect.TypeOf(i1).String())
	}
}

// SetZero z = 0
func (z *e_nocarry_0632) SetZero() *e_nocarry_0632 {
	z[0] = 0
	z[1] = 0
	z[2] = 0
	z[3] = 0
	z[4] = 0
	z[5] = 0
	z[6] = 0
	z[7] = 0
	z[8] = 0
	z[9] = 0
	return z
}

// SetOne z = 1 (in Montgomery form)
func (z *e_nocarry_0632) SetOne() *e_nocarry_0632 {
	z[0] = 7227730580110706203
	z[1] = 5692316793904131446
	z[2] = 7522791657341316021
	z[3] = 9029757652229125315
	z[4] = 12251827174519540797
	z[5] = 5179915244863328038
	z[6] = 16898460423431200337
	z[7] = 3708189780405043063
	z[8] = 12465686623137880016
	z[9] = 12944069285940315
	return z
}

// Div z = x*y^-1 mod q
func (z *e_nocarry_0632) Div(x, y *e_nocarry_0632) *e_nocarry_0632 {
	var yInv e_nocarry_0632
	yInv.Inverse(y)
	z.Mul(x, &yInv)
	return z
}

// Bit returns the i'th bit, with lsb == bit 0.
// It is the responsability of the caller to convert from Montgomery to Regular form if needed
func (z *e_nocarry_0632) Bit(i uint64) uint64 {
	j := i / 64
	if j >= 10 {
		return 0
	}
	return uint64(z[j] >> (i % 64) & 1)
}

// Equal returns z == x
func (z *e_nocarry_0632) Equal(x *e_nocarry_0632) bool {
	return (z[9] == x[9]) && (z[8] == x[8]) && (z[7] == x[7]) && (z[6] == x[6]) && (z[5] == x[5]) && (z[4] == x[4]) && (z[3] == x[3]) && (z[2] == x[2]) && (z[1] == x[1]) && (z[0] == x[0])
}

// IsZero returns z == 0
func (z *e_nocarry_0632) IsZero() bool {
	return (z[9] | z[8] | z[7] | z[6] | z[5] | z[4] | z[3] | z[2] | z[1] | z[0]) == 0
}

// IsUint64 returns true if z[0] >= 0 and all other words are 0
func (z *e_nocarry_0632) IsUint64() bool {
	return (z[9] | z[8] | z[7] | z[6] | z[5] | z[4] | z[3] | z[2] | z[1]) == 0
}

// Cmp compares (lexicographic order) z and x and returns:
//
//   -1 if z <  x
//    0 if z == x
//   +1 if z >  x
//
func (z *e_nocarry_0632) Cmp(x *e_nocarry_0632) int {
	_z := *z
	_x := *x
	_z.FromMont()
	_x.FromMont()
	if _z[9] > _x[9] {
		return 1
	} else if _z[9] < _x[9] {
		return -1
	}
	if _z[8] > _x[8] {
		return 1
	} else if _z[8] < _x[8] {
		return -1
	}
	if _z[7] > _x[7] {
		return 1
	} else if _z[7] < _x[7] {
		return -1
	}
	if _z[6] > _x[6] {
		return 1
	} else if _z[6] < _x[6] {
		return -1
	}
	if _z[5] > _x[5] {
		return 1
	} else if _z[5] < _x[5] {
		return -1
	}
	if _z[4] > _x[4] {
		return 1
	} else if _z[4] < _x[4] {
		return -1
	}
	if _z[3] > _x[3] {
		return 1
	} else if _z[3] < _x[3] {
		return -1
	}
	if _z[2] > _x[2] {
		return 1
	} else if _z[2] < _x[2] {
		return -1
	}
	if _z[1] > _x[1] {
		return 1
	} else if _z[1] < _x[1] {
		return -1
	}
	if _z[0] > _x[0] {
		return 1
	} else if _z[0] < _x[0] {
		return -1
	}
	return 0
}

// LexicographicallyLargest returns true if this element is strictly lexicographically
// larger than its negation, false otherwise
func (z *e_nocarry_0632) LexicographicallyLargest() bool {
	// adapted from github.com/zkcrypto/bls12_381
	// we check if the element is larger than (q-1) / 2
	// if z - (((q -1) / 2) + 1) have no underflow, then z > (q-1) / 2

	_z := *z
	_z.FromMont()

	var b uint64
	_, b = bits.Sub64(_z[0], 9631407023483045045, 0)
	_, b = bits.Sub64(_z[1], 3193921660532178032, b)
	_, b = bits.Sub64(_z[2], 7268411622679487364, b)
	_, b = bits.Sub64(_z[3], 1764107309476835462, b)
	_, b = bits.Sub64(_z[4], 3603128963299912702, b)
	_, b = bits.Sub64(_z[5], 11803301178349338617, b)
	_, b = bits.Sub64(_z[6], 2138655074587910101, b)
	_, b = bits.Sub64(_z[7], 10349561252292371007, b)
	_, b = bits.Sub64(_z[8], 10690187020657410008, b)
	_, b = bits.Sub64(_z[9], 32340000007760721, b)

	return b == 0
}

// SetRandom sets z to a random element < q
func (z *e_nocarry_0632) SetRandom() (*e_nocarry_0632, error) {
	var bytes [80]byte
	if _, err := io.ReadFull(rand.Reader, bytes[:]); err != nil {
		return nil, err
	}
	z[0] = binary.BigEndian.Uint64(bytes[0:8])
	z[1] = binary.BigEndian.Uint64(bytes[8:16])
	z[2] = binary.BigEndian.Uint64(bytes[16:24])
	z[3] = binary.BigEndian.Uint64(bytes[24:32])
	z[4] = binary.BigEndian.Uint64(bytes[32:40])
	z[5] = binary.BigEndian.Uint64(bytes[40:48])
	z[6] = binary.BigEndian.Uint64(bytes[48:56])
	z[7] = binary.BigEndian.Uint64(bytes[56:64])
	z[8] = binary.BigEndian.Uint64(bytes[64:72])
	z[9] = binary.BigEndian.Uint64(bytes[72:80])
	z[9] %= 64680000015521443

	// if z > q --> z -= q
	// note: this is NOT constant time
	if !(z[9] < 64680000015521443 || (z[9] == 64680000015521443 && (z[8] < 2933629967605268401 || (z[8] == 2933629967605268401 && (z[7] < 2252378430875190398 || (z[7] == 2252378430875190398 && (z[6] < 4277310149175820203 || (z[6] == 4277310149175820203 && (z[5] < 5159858282989125618 || (z[5] == 5159858282989125618 && (z[4] < 7206257926599825404 || (z[4] == 7206257926599825404 && (z[3] < 3528214618953670924 || (z[3] == 3528214618953670924 && (z[2] < 14536823245358974728 || (z[2] == 14536823245358974728 && (z[1] < 6387843321064356065 || (z[1] == 6387843321064356065 && (z[0] < 816069973256538473))))))))))))))))))) {
		var b uint64
		z[0], b = bits.Sub64(z[0], 816069973256538473, 0)
		z[1], b = bits.Sub64(z[1], 6387843321064356065, b)
		z[2], b = bits.Sub64(z[2], 14536823245358974728, b)
		z[3], b = bits.Sub64(z[3], 3528214618953670924, b)
		z[4], b = bits.Sub64(z[4], 7206257926599825404, b)
		z[5], b = bits.Sub64(z[5], 5159858282989125618, b)
		z[6], b = bits.Sub64(z[6], 4277310149175820203, b)
		z[7], b = bits.Sub64(z[7], 2252378430875190398, b)
		z[8], b = bits.Sub64(z[8], 2933629967605268401, b)
		z[9], _ = bits.Sub64(z[9], 64680000015521443, b)
	}

	return z, nil
}

// One returns 1 (in montgommery form)
func One() e_nocarry_0632 {
	var one e_nocarry_0632
	one.SetOne()
	return one
}

// Halve sets z to z / 2 (mod p)
func (z *e_nocarry_0632) Halve() {
	if z[0]&1 == 1 {
		var carry uint64

		// z = z + q
		z[0], carry = bits.Add64(z[0], 816069973256538473, 0)
		z[1], carry = bits.Add64(z[1], 6387843321064356065, carry)
		z[2], carry = bits.Add64(z[2], 14536823245358974728, carry)
		z[3], carry = bits.Add64(z[3], 3528214618953670924, carry)
		z[4], carry = bits.Add64(z[4], 7206257926599825404, carry)
		z[5], carry = bits.Add64(z[5], 5159858282989125618, carry)
		z[6], carry = bits.Add64(z[6], 4277310149175820203, carry)
		z[7], carry = bits.Add64(z[7], 2252378430875190398, carry)
		z[8], carry = bits.Add64(z[8], 2933629967605268401, carry)
		z[9], _ = bits.Add64(z[9], 64680000015521443, carry)

	}

	// z = z >> 1

	z[0] = z[0]>>1 | z[1]<<63
	z[1] = z[1]>>1 | z[2]<<63
	z[2] = z[2]>>1 | z[3]<<63
	z[3] = z[3]>>1 | z[4]<<63
	z[4] = z[4]>>1 | z[5]<<63
	z[5] = z[5]>>1 | z[6]<<63
	z[6] = z[6]>>1 | z[7]<<63
	z[7] = z[7]>>1 | z[8]<<63
	z[8] = z[8]>>1 | z[9]<<63
	z[9] >>= 1

}

// API with assembly impl

// Mul z = x * y mod q
// see https://hackmd.io/@zkteam/modular_multiplication
func (z *e_nocarry_0632) Mul(x, y *e_nocarry_0632) *e_nocarry_0632 {
	mul(z, x, y)
	return z
}

// Square z = x * x mod q
// see https://hackmd.io/@zkteam/modular_multiplication
func (z *e_nocarry_0632) Square(x *e_nocarry_0632) *e_nocarry_0632 {
	mul(z, x, x)
	return z
}

// FromMont converts z in place (i.e. mutates) from Montgomery to regular representation
// sets and returns z = z * 1
func (z *e_nocarry_0632) FromMont() *e_nocarry_0632 {
	fromMont(z)
	return z
}

// Add z = x + y mod q
func (z *e_nocarry_0632) Add(x, y *e_nocarry_0632) *e_nocarry_0632 {
	add(z, x, y)
	return z
}

// Double z = x + x mod q, aka Lsh 1
func (z *e_nocarry_0632) Double(x *e_nocarry_0632) *e_nocarry_0632 {
	double(z, x)
	return z
}

// Sub  z = x - y mod q
func (z *e_nocarry_0632) Sub(x, y *e_nocarry_0632) *e_nocarry_0632 {
	sub(z, x, y)
	return z
}

// Neg z = q - x
func (z *e_nocarry_0632) Neg(x *e_nocarry_0632) *e_nocarry_0632 {
	neg(z, x)
	return z
}

// Generic (no ADX instructions, no AMD64) versions of multiplication and squaring algorithms

func _mulGeneric(z, x, y *e_nocarry_0632) {

	var t [10]uint64
	var c [3]uint64
	{
		// round 0
		v := x[0]
		c[1], c[0] = bits.Mul64(v, y[0])
		m := c[0] * 3770451588057426215
		c[2] = madd0(m, 816069973256538473, c[0])
		c[1], c[0] = madd1(v, y[1], c[1])
		c[2], t[0] = madd2(m, 6387843321064356065, c[2], c[0])
		c[1], c[0] = madd1(v, y[2], c[1])
		c[2], t[1] = madd2(m, 14536823245358974728, c[2], c[0])
		c[1], c[0] = madd1(v, y[3], c[1])
		c[2], t[2] = madd2(m, 3528214618953670924, c[2], c[0])
		c[1], c[0] = madd1(v, y[4], c[1])
		c[2], t[3] = madd2(m, 7206257926599825404, c[2], c[0])
		c[1], c[0] = madd1(v, y[5], c[1])
		c[2], t[4] = madd2(m, 5159858282989125618, c[2], c[0])
		c[1], c[0] = madd1(v, y[6], c[1])
		c[2], t[5] = madd2(m, 4277310149175820203, c[2], c[0])
		c[1], c[0] = madd1(v, y[7], c[1])
		c[2], t[6] = madd2(m, 2252378430875190398, c[2], c[0])
		c[1], c[0] = madd1(v, y[8], c[1])
		c[2], t[7] = madd2(m, 2933629967605268401, c[2], c[0])
		c[1], c[0] = madd1(v, y[9], c[1])
		t[9], t[8] = madd3(m, 64680000015521443, c[0], c[2], c[1])
	}
	{
		// round 1
		v := x[1]
		c[1], c[0] = madd1(v, y[0], t[0])
		m := c[0] * 3770451588057426215
		c[2] = madd0(m, 816069973256538473, c[0])
		c[1], c[0] = madd2(v, y[1], c[1], t[1])
		c[2], t[0] = madd2(m, 6387843321064356065, c[2], c[0])
		c[1], c[0] = madd2(v, y[2], c[1], t[2])
		c[2], t[1] = madd2(m, 14536823245358974728, c[2], c[0])
		c[1], c[0] = madd2(v, y[3], c[1], t[3])
		c[2], t[2] = madd2(m, 3528214618953670924, c[2], c[0])
		c[1], c[0] = madd2(v, y[4], c[1], t[4])
		c[2], t[3] = madd2(m, 7206257926599825404, c[2], c[0])
		c[1], c[0] = madd2(v, y[5], c[1], t[5])
		c[2], t[4] = madd2(m, 5159858282989125618, c[2], c[0])
		c[1], c[0] = madd2(v, y[6], c[1], t[6])
		c[2], t[5] = madd2(m, 4277310149175820203, c[2], c[0])
		c[1], c[0] = madd2(v, y[7], c[1], t[7])
		c[2], t[6] = madd2(m, 2252378430875190398, c[2], c[0])
		c[1], c[0] = madd2(v, y[8], c[1], t[8])
		c[2], t[7] = madd2(m, 2933629967605268401, c[2], c[0])
		c[1], c[0] = madd2(v, y[9], c[1], t[9])
		t[9], t[8] = madd3(m, 64680000015521443, c[0], c[2], c[1])
	}
	{
		// round 2
		v := x[2]
		c[1], c[0] = madd1(v, y[0], t[0])
		m := c[0] * 3770451588057426215
		c[2] = madd0(m, 816069973256538473, c[0])
		c[1], c[0] = madd2(v, y[1], c[1], t[1])
		c[2], t[0] = madd2(m, 6387843321064356065, c[2], c[0])
		c[1], c[0] = madd2(v, y[2], c[1], t[2])
		c[2], t[1] = madd2(m, 14536823245358974728, c[2], c[0])
		c[1], c[0] = madd2(v, y[3], c[1], t[3])
		c[2], t[2] = madd2(m, 3528214618953670924, c[2], c[0])
		c[1], c[0] = madd2(v, y[4], c[1], t[4])
		c[2], t[3] = madd2(m, 7206257926599825404, c[2], c[0])
		c[1], c[0] = madd2(v, y[5], c[1], t[5])
		c[2], t[4] = madd2(m, 5159858282989125618, c[2], c[0])
		c[1], c[0] = madd2(v, y[6], c[1], t[6])
		c[2], t[5] = madd2(m, 4277310149175820203, c[2], c[0])
		c[1], c[0] = madd2(v, y[7], c[1], t[7])
		c[2], t[6] = madd2(m, 2252378430875190398, c[2], c[0])
		c[1], c[0] = madd2(v, y[8], c[1], t[8])
		c[2], t[7] = madd2(m, 2933629967605268401, c[2], c[0])
		c[1], c[0] = madd2(v, y[9], c[1], t[9])
		t[9], t[8] = madd3(m, 64680000015521443, c[0], c[2], c[1])
	}
	{
		// round 3
		v := x[3]
		c[1], c[0] = madd1(v, y[0], t[0])
		m := c[0] * 3770451588057426215
		c[2] = madd0(m, 816069973256538473, c[0])
		c[1], c[0] = madd2(v, y[1], c[1], t[1])
		c[2], t[0] = madd2(m, 6387843321064356065, c[2], c[0])
		c[1], c[0] = madd2(v, y[2], c[1], t[2])
		c[2], t[1] = madd2(m, 14536823245358974728, c[2], c[0])
		c[1], c[0] = madd2(v, y[3], c[1], t[3])
		c[2], t[2] = madd2(m, 3528214618953670924, c[2], c[0])
		c[1], c[0] = madd2(v, y[4], c[1], t[4])
		c[2], t[3] = madd2(m, 7206257926599825404, c[2], c[0])
		c[1], c[0] = madd2(v, y[5], c[1], t[5])
		c[2], t[4] = madd2(m, 5159858282989125618, c[2], c[0])
		c[1], c[0] = madd2(v, y[6], c[1], t[6])
		c[2], t[5] = madd2(m, 4277310149175820203, c[2], c[0])
		c[1], c[0] = madd2(v, y[7], c[1], t[7])
		c[2], t[6] = madd2(m, 2252378430875190398, c[2], c[0])
		c[1], c[0] = madd2(v, y[8], c[1], t[8])
		c[2], t[7] = madd2(m, 2933629967605268401, c[2], c[0])
		c[1], c[0] = madd2(v, y[9], c[1], t[9])
		t[9], t[8] = madd3(m, 64680000015521443, c[0], c[2], c[1])
	}
	{
		// round 4
		v := x[4]
		c[1], c[0] = madd1(v, y[0], t[0])
		m := c[0] * 3770451588057426215
		c[2] = madd0(m, 816069973256538473, c[0])
		c[1], c[0] = madd2(v, y[1], c[1], t[1])
		c[2], t[0] = madd2(m, 6387843321064356065, c[2], c[0])
		c[1], c[0] = madd2(v, y[2], c[1], t[2])
		c[2], t[1] = madd2(m, 14536823245358974728, c[2], c[0])
		c[1], c[0] = madd2(v, y[3], c[1], t[3])
		c[2], t[2] = madd2(m, 3528214618953670924, c[2], c[0])
		c[1], c[0] = madd2(v, y[4], c[1], t[4])
		c[2], t[3] = madd2(m, 7206257926599825404, c[2], c[0])
		c[1], c[0] = madd2(v, y[5], c[1], t[5])
		c[2], t[4] = madd2(m, 5159858282989125618, c[2], c[0])
		c[1], c[0] = madd2(v, y[6], c[1], t[6])
		c[2], t[5] = madd2(m, 4277310149175820203, c[2], c[0])
		c[1], c[0] = madd2(v, y[7], c[1], t[7])
		c[2], t[6] = madd2(m, 2252378430875190398, c[2], c[0])
		c[1], c[0] = madd2(v, y[8], c[1], t[8])
		c[2], t[7] = madd2(m, 2933629967605268401, c[2], c[0])
		c[1], c[0] = madd2(v, y[9], c[1], t[9])
		t[9], t[8] = madd3(m, 64680000015521443, c[0], c[2], c[1])
	}
	{
		// round 5
		v := x[5]
		c[1], c[0] = madd1(v, y[0], t[0])
		m := c[0] * 3770451588057426215
		c[2] = madd0(m, 816069973256538473, c[0])
		c[1], c[0] = madd2(v, y[1], c[1], t[1])
		c[2], t[0] = madd2(m, 6387843321064356065, c[2], c[0])
		c[1], c[0] = madd2(v, y[2], c[1], t[2])
		c[2], t[1] = madd2(m, 14536823245358974728, c[2], c[0])
		c[1], c[0] = madd2(v, y[3], c[1], t[3])
		c[2], t[2] = madd2(m, 3528214618953670924, c[2], c[0])
		c[1], c[0] = madd2(v, y[4], c[1], t[4])
		c[2], t[3] = madd2(m, 7206257926599825404, c[2], c[0])
		c[1], c[0] = madd2(v, y[5], c[1], t[5])
		c[2], t[4] = madd2(m, 5159858282989125618, c[2], c[0])
		c[1], c[0] = madd2(v, y[6], c[1], t[6])
		c[2], t[5] = madd2(m, 4277310149175820203, c[2], c[0])
		c[1], c[0] = madd2(v, y[7], c[1], t[7])
		c[2], t[6] = madd2(m, 2252378430875190398, c[2], c[0])
		c[1], c[0] = madd2(v, y[8], c[1], t[8])
		c[2], t[7] = madd2(m, 2933629967605268401, c[2], c[0])
		c[1], c[0] = madd2(v, y[9], c[1], t[9])
		t[9], t[8] = madd3(m, 64680000015521443, c[0], c[2], c[1])
	}
	{
		// round 6
		v := x[6]
		c[1], c[0] = madd1(v, y[0], t[0])
		m := c[0] * 3770451588057426215
		c[2] = madd0(m, 816069973256538473, c[0])
		c[1], c[0] = madd2(v, y[1], c[1], t[1])
		c[2], t[0] = madd2(m, 6387843321064356065, c[2], c[0])
		c[1], c[0] = madd2(v, y[2], c[1], t[2])
		c[2], t[1] = madd2(m, 14536823245358974728, c[2], c[0])
		c[1], c[0] = madd2(v, y[3], c[1], t[3])
		c[2], t[2] = madd2(m, 3528214618953670924, c[2], c[0])
		c[1], c[0] = madd2(v, y[4], c[1], t[4])
		c[2], t[3] = madd2(m, 7206257926599825404, c[2], c[0])
		c[1], c[0] = madd2(v, y[5], c[1], t[5])
		c[2], t[4] = madd2(m, 5159858282989125618, c[2], c[0])
		c[1], c[0] = madd2(v, y[6], c[1], t[6])
		c[2], t[5] = madd2(m, 4277310149175820203, c[2], c[0])
		c[1], c[0] = madd2(v, y[7], c[1], t[7])
		c[2], t[6] = madd2(m, 2252378430875190398, c[2], c[0])
		c[1], c[0] = madd2(v, y[8], c[1], t[8])
		c[2], t[7] = madd2(m, 2933629967605268401, c[2], c[0])
		c[1], c[0] = madd2(v, y[9], c[1], t[9])
		t[9], t[8] = madd3(m, 64680000015521443, c[0], c[2], c[1])
	}
	{
		// round 7
		v := x[7]
		c[1], c[0] = madd1(v, y[0], t[0])
		m := c[0] * 3770451588057426215
		c[2] = madd0(m, 816069973256538473, c[0])
		c[1], c[0] = madd2(v, y[1], c[1], t[1])
		c[2], t[0] = madd2(m, 6387843321064356065, c[2], c[0])
		c[1], c[0] = madd2(v, y[2], c[1], t[2])
		c[2], t[1] = madd2(m, 14536823245358974728, c[2], c[0])
		c[1], c[0] = madd2(v, y[3], c[1], t[3])
		c[2], t[2] = madd2(m, 3528214618953670924, c[2], c[0])
		c[1], c[0] = madd2(v, y[4], c[1], t[4])
		c[2], t[3] = madd2(m, 7206257926599825404, c[2], c[0])
		c[1], c[0] = madd2(v, y[5], c[1], t[5])
		c[2], t[4] = madd2(m, 5159858282989125618, c[2], c[0])
		c[1], c[0] = madd2(v, y[6], c[1], t[6])
		c[2], t[5] = madd2(m, 4277310149175820203, c[2], c[0])
		c[1], c[0] = madd2(v, y[7], c[1], t[7])
		c[2], t[6] = madd2(m, 2252378430875190398, c[2], c[0])
		c[1], c[0] = madd2(v, y[8], c[1], t[8])
		c[2], t[7] = madd2(m, 2933629967605268401, c[2], c[0])
		c[1], c[0] = madd2(v, y[9], c[1], t[9])
		t[9], t[8] = madd3(m, 64680000015521443, c[0], c[2], c[1])
	}
	{
		// round 8
		v := x[8]
		c[1], c[0] = madd1(v, y[0], t[0])
		m := c[0] * 3770451588057426215
		c[2] = madd0(m, 816069973256538473, c[0])
		c[1], c[0] = madd2(v, y[1], c[1], t[1])
		c[2], t[0] = madd2(m, 6387843321064356065, c[2], c[0])
		c[1], c[0] = madd2(v, y[2], c[1], t[2])
		c[2], t[1] = madd2(m, 14536823245358974728, c[2], c[0])
		c[1], c[0] = madd2(v, y[3], c[1], t[3])
		c[2], t[2] = madd2(m, 3528214618953670924, c[2], c[0])
		c[1], c[0] = madd2(v, y[4], c[1], t[4])
		c[2], t[3] = madd2(m, 7206257926599825404, c[2], c[0])
		c[1], c[0] = madd2(v, y[5], c[1], t[5])
		c[2], t[4] = madd2(m, 5159858282989125618, c[2], c[0])
		c[1], c[0] = madd2(v, y[6], c[1], t[6])
		c[2], t[5] = madd2(m, 4277310149175820203, c[2], c[0])
		c[1], c[0] = madd2(v, y[7], c[1], t[7])
		c[2], t[6] = madd2(m, 2252378430875190398, c[2], c[0])
		c[1], c[0] = madd2(v, y[8], c[1], t[8])
		c[2], t[7] = madd2(m, 2933629967605268401, c[2], c[0])
		c[1], c[0] = madd2(v, y[9], c[1], t[9])
		t[9], t[8] = madd3(m, 64680000015521443, c[0], c[2], c[1])
	}
	{
		// round 9
		v := x[9]
		c[1], c[0] = madd1(v, y[0], t[0])
		m := c[0] * 3770451588057426215
		c[2] = madd0(m, 816069973256538473, c[0])
		c[1], c[0] = madd2(v, y[1], c[1], t[1])
		c[2], z[0] = madd2(m, 6387843321064356065, c[2], c[0])
		c[1], c[0] = madd2(v, y[2], c[1], t[2])
		c[2], z[1] = madd2(m, 14536823245358974728, c[2], c[0])
		c[1], c[0] = madd2(v, y[3], c[1], t[3])
		c[2], z[2] = madd2(m, 3528214618953670924, c[2], c[0])
		c[1], c[0] = madd2(v, y[4], c[1], t[4])
		c[2], z[3] = madd2(m, 7206257926599825404, c[2], c[0])
		c[1], c[0] = madd2(v, y[5], c[1], t[5])
		c[2], z[4] = madd2(m, 5159858282989125618, c[2], c[0])
		c[1], c[0] = madd2(v, y[6], c[1], t[6])
		c[2], z[5] = madd2(m, 4277310149175820203, c[2], c[0])
		c[1], c[0] = madd2(v, y[7], c[1], t[7])
		c[2], z[6] = madd2(m, 2252378430875190398, c[2], c[0])
		c[1], c[0] = madd2(v, y[8], c[1], t[8])
		c[2], z[7] = madd2(m, 2933629967605268401, c[2], c[0])
		c[1], c[0] = madd2(v, y[9], c[1], t[9])
		z[9], z[8] = madd3(m, 64680000015521443, c[0], c[2], c[1])
	}

	// if z > q --> z -= q
	// note: this is NOT constant time
	if !(z[9] < 64680000015521443 || (z[9] == 64680000015521443 && (z[8] < 2933629967605268401 || (z[8] == 2933629967605268401 && (z[7] < 2252378430875190398 || (z[7] == 2252378430875190398 && (z[6] < 4277310149175820203 || (z[6] == 4277310149175820203 && (z[5] < 5159858282989125618 || (z[5] == 5159858282989125618 && (z[4] < 7206257926599825404 || (z[4] == 7206257926599825404 && (z[3] < 3528214618953670924 || (z[3] == 3528214618953670924 && (z[2] < 14536823245358974728 || (z[2] == 14536823245358974728 && (z[1] < 6387843321064356065 || (z[1] == 6387843321064356065 && (z[0] < 816069973256538473))))))))))))))))))) {
		var b uint64
		z[0], b = bits.Sub64(z[0], 816069973256538473, 0)
		z[1], b = bits.Sub64(z[1], 6387843321064356065, b)
		z[2], b = bits.Sub64(z[2], 14536823245358974728, b)
		z[3], b = bits.Sub64(z[3], 3528214618953670924, b)
		z[4], b = bits.Sub64(z[4], 7206257926599825404, b)
		z[5], b = bits.Sub64(z[5], 5159858282989125618, b)
		z[6], b = bits.Sub64(z[6], 4277310149175820203, b)
		z[7], b = bits.Sub64(z[7], 2252378430875190398, b)
		z[8], b = bits.Sub64(z[8], 2933629967605268401, b)
		z[9], _ = bits.Sub64(z[9], 64680000015521443, b)
	}
}

func _mulWGeneric(z, x *e_nocarry_0632, y uint64) {

	var t [10]uint64
	{
		// round 0
		c1, c0 := bits.Mul64(y, x[0])
		m := c0 * 3770451588057426215
		c2 := madd0(m, 816069973256538473, c0)
		c1, c0 = madd1(y, x[1], c1)
		c2, t[0] = madd2(m, 6387843321064356065, c2, c0)
		c1, c0 = madd1(y, x[2], c1)
		c2, t[1] = madd2(m, 14536823245358974728, c2, c0)
		c1, c0 = madd1(y, x[3], c1)
		c2, t[2] = madd2(m, 3528214618953670924, c2, c0)
		c1, c0 = madd1(y, x[4], c1)
		c2, t[3] = madd2(m, 7206257926599825404, c2, c0)
		c1, c0 = madd1(y, x[5], c1)
		c2, t[4] = madd2(m, 5159858282989125618, c2, c0)
		c1, c0 = madd1(y, x[6], c1)
		c2, t[5] = madd2(m, 4277310149175820203, c2, c0)
		c1, c0 = madd1(y, x[7], c1)
		c2, t[6] = madd2(m, 2252378430875190398, c2, c0)
		c1, c0 = madd1(y, x[8], c1)
		c2, t[7] = madd2(m, 2933629967605268401, c2, c0)
		c1, c0 = madd1(y, x[9], c1)
		t[9], t[8] = madd3(m, 64680000015521443, c0, c2, c1)
	}
	{
		// round 1
		m := t[0] * 3770451588057426215
		c2 := madd0(m, 816069973256538473, t[0])
		c2, t[0] = madd2(m, 6387843321064356065, c2, t[1])
		c2, t[1] = madd2(m, 14536823245358974728, c2, t[2])
		c2, t[2] = madd2(m, 3528214618953670924, c2, t[3])
		c2, t[3] = madd2(m, 7206257926599825404, c2, t[4])
		c2, t[4] = madd2(m, 5159858282989125618, c2, t[5])
		c2, t[5] = madd2(m, 4277310149175820203, c2, t[6])
		c2, t[6] = madd2(m, 2252378430875190398, c2, t[7])
		c2, t[7] = madd2(m, 2933629967605268401, c2, t[8])
		t[9], t[8] = madd2(m, 64680000015521443, t[9], c2)
	}
	{
		// round 2
		m := t[0] * 3770451588057426215
		c2 := madd0(m, 816069973256538473, t[0])
		c2, t[0] = madd2(m, 6387843321064356065, c2, t[1])
		c2, t[1] = madd2(m, 14536823245358974728, c2, t[2])
		c2, t[2] = madd2(m, 3528214618953670924, c2, t[3])
		c2, t[3] = madd2(m, 7206257926599825404, c2, t[4])
		c2, t[4] = madd2(m, 5159858282989125618, c2, t[5])
		c2, t[5] = madd2(m, 4277310149175820203, c2, t[6])
		c2, t[6] = madd2(m, 2252378430875190398, c2, t[7])
		c2, t[7] = madd2(m, 2933629967605268401, c2, t[8])
		t[9], t[8] = madd2(m, 64680000015521443, t[9], c2)
	}
	{
		// round 3
		m := t[0] * 3770451588057426215
		c2 := madd0(m, 816069973256538473, t[0])
		c2, t[0] = madd2(m, 6387843321064356065, c2, t[1])
		c2, t[1] = madd2(m, 14536823245358974728, c2, t[2])
		c2, t[2] = madd2(m, 3528214618953670924, c2, t[3])
		c2, t[3] = madd2(m, 7206257926599825404, c2, t[4])
		c2, t[4] = madd2(m, 5159858282989125618, c2, t[5])
		c2, t[5] = madd2(m, 4277310149175820203, c2, t[6])
		c2, t[6] = madd2(m, 2252378430875190398, c2, t[7])
		c2, t[7] = madd2(m, 2933629967605268401, c2, t[8])
		t[9], t[8] = madd2(m, 64680000015521443, t[9], c2)
	}
	{
		// round 4
		m := t[0] * 3770451588057426215
		c2 := madd0(m, 816069973256538473, t[0])
		c2, t[0] = madd2(m, 6387843321064356065, c2, t[1])
		c2, t[1] = madd2(m, 14536823245358974728, c2, t[2])
		c2, t[2] = madd2(m, 3528214618953670924, c2, t[3])
		c2, t[3] = madd2(m, 7206257926599825404, c2, t[4])
		c2, t[4] = madd2(m, 5159858282989125618, c2, t[5])
		c2, t[5] = madd2(m, 4277310149175820203, c2, t[6])
		c2, t[6] = madd2(m, 2252378430875190398, c2, t[7])
		c2, t[7] = madd2(m, 2933629967605268401, c2, t[8])
		t[9], t[8] = madd2(m, 64680000015521443, t[9], c2)
	}
	{
		// round 5
		m := t[0] * 3770451588057426215
		c2 := madd0(m, 816069973256538473, t[0])
		c2, t[0] = madd2(m, 6387843321064356065, c2, t[1])
		c2, t[1] = madd2(m, 14536823245358974728, c2, t[2])
		c2, t[2] = madd2(m, 3528214618953670924, c2, t[3])
		c2, t[3] = madd2(m, 7206257926599825404, c2, t[4])
		c2, t[4] = madd2(m, 5159858282989125618, c2, t[5])
		c2, t[5] = madd2(m, 4277310149175820203, c2, t[6])
		c2, t[6] = madd2(m, 2252378430875190398, c2, t[7])
		c2, t[7] = madd2(m, 2933629967605268401, c2, t[8])
		t[9], t[8] = madd2(m, 64680000015521443, t[9], c2)
	}
	{
		// round 6
		m := t[0] * 3770451588057426215
		c2 := madd0(m, 816069973256538473, t[0])
		c2, t[0] = madd2(m, 6387843321064356065, c2, t[1])
		c2, t[1] = madd2(m, 14536823245358974728, c2, t[2])
		c2, t[2] = madd2(m, 3528214618953670924, c2, t[3])
		c2, t[3] = madd2(m, 7206257926599825404, c2, t[4])
		c2, t[4] = madd2(m, 5159858282989125618, c2, t[5])
		c2, t[5] = madd2(m, 4277310149175820203, c2, t[6])
		c2, t[6] = madd2(m, 2252378430875190398, c2, t[7])
		c2, t[7] = madd2(m, 2933629967605268401, c2, t[8])
		t[9], t[8] = madd2(m, 64680000015521443, t[9], c2)
	}
	{
		// round 7
		m := t[0] * 3770451588057426215
		c2 := madd0(m, 816069973256538473, t[0])
		c2, t[0] = madd2(m, 6387843321064356065, c2, t[1])
		c2, t[1] = madd2(m, 14536823245358974728, c2, t[2])
		c2, t[2] = madd2(m, 3528214618953670924, c2, t[3])
		c2, t[3] = madd2(m, 7206257926599825404, c2, t[4])
		c2, t[4] = madd2(m, 5159858282989125618, c2, t[5])
		c2, t[5] = madd2(m, 4277310149175820203, c2, t[6])
		c2, t[6] = madd2(m, 2252378430875190398, c2, t[7])
		c2, t[7] = madd2(m, 2933629967605268401, c2, t[8])
		t[9], t[8] = madd2(m, 64680000015521443, t[9], c2)
	}
	{
		// round 8
		m := t[0] * 3770451588057426215
		c2 := madd0(m, 816069973256538473, t[0])
		c2, t[0] = madd2(m, 6387843321064356065, c2, t[1])
		c2, t[1] = madd2(m, 14536823245358974728, c2, t[2])
		c2, t[2] = madd2(m, 3528214618953670924, c2, t[3])
		c2, t[3] = madd2(m, 7206257926599825404, c2, t[4])
		c2, t[4] = madd2(m, 5159858282989125618, c2, t[5])
		c2, t[5] = madd2(m, 4277310149175820203, c2, t[6])
		c2, t[6] = madd2(m, 2252378430875190398, c2, t[7])
		c2, t[7] = madd2(m, 2933629967605268401, c2, t[8])
		t[9], t[8] = madd2(m, 64680000015521443, t[9], c2)
	}
	{
		// round 9
		m := t[0] * 3770451588057426215
		c2 := madd0(m, 816069973256538473, t[0])
		c2, z[0] = madd2(m, 6387843321064356065, c2, t[1])
		c2, z[1] = madd2(m, 14536823245358974728, c2, t[2])
		c2, z[2] = madd2(m, 3528214618953670924, c2, t[3])
		c2, z[3] = madd2(m, 7206257926599825404, c2, t[4])
		c2, z[4] = madd2(m, 5159858282989125618, c2, t[5])
		c2, z[5] = madd2(m, 4277310149175820203, c2, t[6])
		c2, z[6] = madd2(m, 2252378430875190398, c2, t[7])
		c2, z[7] = madd2(m, 2933629967605268401, c2, t[8])
		z[9], z[8] = madd2(m, 64680000015521443, t[9], c2)
	}

	// if z > q --> z -= q
	// note: this is NOT constant time
	if !(z[9] < 64680000015521443 || (z[9] == 64680000015521443 && (z[8] < 2933629967605268401 || (z[8] == 2933629967605268401 && (z[7] < 2252378430875190398 || (z[7] == 2252378430875190398 && (z[6] < 4277310149175820203 || (z[6] == 4277310149175820203 && (z[5] < 5159858282989125618 || (z[5] == 5159858282989125618 && (z[4] < 7206257926599825404 || (z[4] == 7206257926599825404 && (z[3] < 3528214618953670924 || (z[3] == 3528214618953670924 && (z[2] < 14536823245358974728 || (z[2] == 14536823245358974728 && (z[1] < 6387843321064356065 || (z[1] == 6387843321064356065 && (z[0] < 816069973256538473))))))))))))))))))) {
		var b uint64
		z[0], b = bits.Sub64(z[0], 816069973256538473, 0)
		z[1], b = bits.Sub64(z[1], 6387843321064356065, b)
		z[2], b = bits.Sub64(z[2], 14536823245358974728, b)
		z[3], b = bits.Sub64(z[3], 3528214618953670924, b)
		z[4], b = bits.Sub64(z[4], 7206257926599825404, b)
		z[5], b = bits.Sub64(z[5], 5159858282989125618, b)
		z[6], b = bits.Sub64(z[6], 4277310149175820203, b)
		z[7], b = bits.Sub64(z[7], 2252378430875190398, b)
		z[8], b = bits.Sub64(z[8], 2933629967605268401, b)
		z[9], _ = bits.Sub64(z[9], 64680000015521443, b)
	}
}

func _fromMontGeneric(z *e_nocarry_0632) {
	// the following lines implement z = z * 1
	// with a modified CIOS montgomery multiplication
	{
		// m = z[0]n'[0] mod W
		m := z[0] * 3770451588057426215
		C := madd0(m, 816069973256538473, z[0])
		C, z[0] = madd2(m, 6387843321064356065, z[1], C)
		C, z[1] = madd2(m, 14536823245358974728, z[2], C)
		C, z[2] = madd2(m, 3528214618953670924, z[3], C)
		C, z[3] = madd2(m, 7206257926599825404, z[4], C)
		C, z[4] = madd2(m, 5159858282989125618, z[5], C)
		C, z[5] = madd2(m, 4277310149175820203, z[6], C)
		C, z[6] = madd2(m, 2252378430875190398, z[7], C)
		C, z[7] = madd2(m, 2933629967605268401, z[8], C)
		C, z[8] = madd2(m, 64680000015521443, z[9], C)
		z[9] = C
	}
	{
		// m = z[0]n'[0] mod W
		m := z[0] * 3770451588057426215
		C := madd0(m, 816069973256538473, z[0])
		C, z[0] = madd2(m, 6387843321064356065, z[1], C)
		C, z[1] = madd2(m, 14536823245358974728, z[2], C)
		C, z[2] = madd2(m, 3528214618953670924, z[3], C)
		C, z[3] = madd2(m, 7206257926599825404, z[4], C)
		C, z[4] = madd2(m, 5159858282989125618, z[5], C)
		C, z[5] = madd2(m, 4277310149175820203, z[6], C)
		C, z[6] = madd2(m, 2252378430875190398, z[7], C)
		C, z[7] = madd2(m, 2933629967605268401, z[8], C)
		C, z[8] = madd2(m, 64680000015521443, z[9], C)
		z[9] = C
	}
	{
		// m = z[0]n'[0] mod W
		m := z[0] * 3770451588057426215
		C := madd0(m, 816069973256538473, z[0])
		C, z[0] = madd2(m, 6387843321064356065, z[1], C)
		C, z[1] = madd2(m, 14536823245358974728, z[2], C)
		C, z[2] = madd2(m, 3528214618953670924, z[3], C)
		C, z[3] = madd2(m, 7206257926599825404, z[4], C)
		C, z[4] = madd2(m, 5159858282989125618, z[5], C)
		C, z[5] = madd2(m, 4277310149175820203, z[6], C)
		C, z[6] = madd2(m, 2252378430875190398, z[7], C)
		C, z[7] = madd2(m, 2933629967605268401, z[8], C)
		C, z[8] = madd2(m, 64680000015521443, z[9], C)
		z[9] = C
	}
	{
		// m = z[0]n'[0] mod W
		m := z[0] * 3770451588057426215
		C := madd0(m, 816069973256538473, z[0])
		C, z[0] = madd2(m, 6387843321064356065, z[1], C)
		C, z[1] = madd2(m, 14536823245358974728, z[2], C)
		C, z[2] = madd2(m, 3528214618953670924, z[3], C)
		C, z[3] = madd2(m, 7206257926599825404, z[4], C)
		C, z[4] = madd2(m, 5159858282989125618, z[5], C)
		C, z[5] = madd2(m, 4277310149175820203, z[6], C)
		C, z[6] = madd2(m, 2252378430875190398, z[7], C)
		C, z[7] = madd2(m, 2933629967605268401, z[8], C)
		C, z[8] = madd2(m, 64680000015521443, z[9], C)
		z[9] = C
	}
	{
		// m = z[0]n'[0] mod W
		m := z[0] * 3770451588057426215
		C := madd0(m, 816069973256538473, z[0])
		C, z[0] = madd2(m, 6387843321064356065, z[1], C)
		C, z[1] = madd2(m, 14536823245358974728, z[2], C)
		C, z[2] = madd2(m, 3528214618953670924, z[3], C)
		C, z[3] = madd2(m, 7206257926599825404, z[4], C)
		C, z[4] = madd2(m, 5159858282989125618, z[5], C)
		C, z[5] = madd2(m, 4277310149175820203, z[6], C)
		C, z[6] = madd2(m, 2252378430875190398, z[7], C)
		C, z[7] = madd2(m, 2933629967605268401, z[8], C)
		C, z[8] = madd2(m, 64680000015521443, z[9], C)
		z[9] = C
	}
	{
		// m = z[0]n'[0] mod W
		m := z[0] * 3770451588057426215
		C := madd0(m, 816069973256538473, z[0])
		C, z[0] = madd2(m, 6387843321064356065, z[1], C)
		C, z[1] = madd2(m, 14536823245358974728, z[2], C)
		C, z[2] = madd2(m, 3528214618953670924, z[3], C)
		C, z[3] = madd2(m, 7206257926599825404, z[4], C)
		C, z[4] = madd2(m, 5159858282989125618, z[5], C)
		C, z[5] = madd2(m, 4277310149175820203, z[6], C)
		C, z[6] = madd2(m, 2252378430875190398, z[7], C)
		C, z[7] = madd2(m, 2933629967605268401, z[8], C)
		C, z[8] = madd2(m, 64680000015521443, z[9], C)
		z[9] = C
	}
	{
		// m = z[0]n'[0] mod W
		m := z[0] * 3770451588057426215
		C := madd0(m, 816069973256538473, z[0])
		C, z[0] = madd2(m, 6387843321064356065, z[1], C)
		C, z[1] = madd2(m, 14536823245358974728, z[2], C)
		C, z[2] = madd2(m, 3528214618953670924, z[3], C)
		C, z[3] = madd2(m, 7206257926599825404, z[4], C)
		C, z[4] = madd2(m, 5159858282989125618, z[5], C)
		C, z[5] = madd2(m, 4277310149175820203, z[6], C)
		C, z[6] = madd2(m, 2252378430875190398, z[7], C)
		C, z[7] = madd2(m, 2933629967605268401, z[8], C)
		C, z[8] = madd2(m, 64680000015521443, z[9], C)
		z[9] = C
	}
	{
		// m = z[0]n'[0] mod W
		m := z[0] * 3770451588057426215
		C := madd0(m, 816069973256538473, z[0])
		C, z[0] = madd2(m, 6387843321064356065, z[1], C)
		C, z[1] = madd2(m, 14536823245358974728, z[2], C)
		C, z[2] = madd2(m, 3528214618953670924, z[3], C)
		C, z[3] = madd2(m, 7206257926599825404, z[4], C)
		C, z[4] = madd2(m, 5159858282989125618, z[5], C)
		C, z[5] = madd2(m, 4277310149175820203, z[6], C)
		C, z[6] = madd2(m, 2252378430875190398, z[7], C)
		C, z[7] = madd2(m, 2933629967605268401, z[8], C)
		C, z[8] = madd2(m, 64680000015521443, z[9], C)
		z[9] = C
	}
	{
		// m = z[0]n'[0] mod W
		m := z[0] * 3770451588057426215
		C := madd0(m, 816069973256538473, z[0])
		C, z[0] = madd2(m, 6387843321064356065, z[1], C)
		C, z[1] = madd2(m, 14536823245358974728, z[2], C)
		C, z[2] = madd2(m, 3528214618953670924, z[3], C)
		C, z[3] = madd2(m, 7206257926599825404, z[4], C)
		C, z[4] = madd2(m, 5159858282989125618, z[5], C)
		C, z[5] = madd2(m, 4277310149175820203, z[6], C)
		C, z[6] = madd2(m, 2252378430875190398, z[7], C)
		C, z[7] = madd2(m, 2933629967605268401, z[8], C)
		C, z[8] = madd2(m, 64680000015521443, z[9], C)
		z[9] = C
	}
	{
		// m = z[0]n'[0] mod W
		m := z[0] * 3770451588057426215
		C := madd0(m, 816069973256538473, z[0])
		C, z[0] = madd2(m, 6387843321064356065, z[1], C)
		C, z[1] = madd2(m, 14536823245358974728, z[2], C)
		C, z[2] = madd2(m, 3528214618953670924, z[3], C)
		C, z[3] = madd2(m, 7206257926599825404, z[4], C)
		C, z[4] = madd2(m, 5159858282989125618, z[5], C)
		C, z[5] = madd2(m, 4277310149175820203, z[6], C)
		C, z[6] = madd2(m, 2252378430875190398, z[7], C)
		C, z[7] = madd2(m, 2933629967605268401, z[8], C)
		C, z[8] = madd2(m, 64680000015521443, z[9], C)
		z[9] = C
	}

	// if z > q --> z -= q
	// note: this is NOT constant time
	if !(z[9] < 64680000015521443 || (z[9] == 64680000015521443 && (z[8] < 2933629967605268401 || (z[8] == 2933629967605268401 && (z[7] < 2252378430875190398 || (z[7] == 2252378430875190398 && (z[6] < 4277310149175820203 || (z[6] == 4277310149175820203 && (z[5] < 5159858282989125618 || (z[5] == 5159858282989125618 && (z[4] < 7206257926599825404 || (z[4] == 7206257926599825404 && (z[3] < 3528214618953670924 || (z[3] == 3528214618953670924 && (z[2] < 14536823245358974728 || (z[2] == 14536823245358974728 && (z[1] < 6387843321064356065 || (z[1] == 6387843321064356065 && (z[0] < 816069973256538473))))))))))))))))))) {
		var b uint64
		z[0], b = bits.Sub64(z[0], 816069973256538473, 0)
		z[1], b = bits.Sub64(z[1], 6387843321064356065, b)
		z[2], b = bits.Sub64(z[2], 14536823245358974728, b)
		z[3], b = bits.Sub64(z[3], 3528214618953670924, b)
		z[4], b = bits.Sub64(z[4], 7206257926599825404, b)
		z[5], b = bits.Sub64(z[5], 5159858282989125618, b)
		z[6], b = bits.Sub64(z[6], 4277310149175820203, b)
		z[7], b = bits.Sub64(z[7], 2252378430875190398, b)
		z[8], b = bits.Sub64(z[8], 2933629967605268401, b)
		z[9], _ = bits.Sub64(z[9], 64680000015521443, b)
	}
}

func _addGeneric(z, x, y *e_nocarry_0632) {
	var carry uint64

	z[0], carry = bits.Add64(x[0], y[0], 0)
	z[1], carry = bits.Add64(x[1], y[1], carry)
	z[2], carry = bits.Add64(x[2], y[2], carry)
	z[3], carry = bits.Add64(x[3], y[3], carry)
	z[4], carry = bits.Add64(x[4], y[4], carry)
	z[5], carry = bits.Add64(x[5], y[5], carry)
	z[6], carry = bits.Add64(x[6], y[6], carry)
	z[7], carry = bits.Add64(x[7], y[7], carry)
	z[8], carry = bits.Add64(x[8], y[8], carry)
	z[9], _ = bits.Add64(x[9], y[9], carry)

	// if z > q --> z -= q
	// note: this is NOT constant time
	if !(z[9] < 64680000015521443 || (z[9] == 64680000015521443 && (z[8] < 2933629967605268401 || (z[8] == 2933629967605268401 && (z[7] < 2252378430875190398 || (z[7] == 2252378430875190398 && (z[6] < 4277310149175820203 || (z[6] == 4277310149175820203 && (z[5] < 5159858282989125618 || (z[5] == 5159858282989125618 && (z[4] < 7206257926599825404 || (z[4] == 7206257926599825404 && (z[3] < 3528214618953670924 || (z[3] == 3528214618953670924 && (z[2] < 14536823245358974728 || (z[2] == 14536823245358974728 && (z[1] < 6387843321064356065 || (z[1] == 6387843321064356065 && (z[0] < 816069973256538473))))))))))))))))))) {
		var b uint64
		z[0], b = bits.Sub64(z[0], 816069973256538473, 0)
		z[1], b = bits.Sub64(z[1], 6387843321064356065, b)
		z[2], b = bits.Sub64(z[2], 14536823245358974728, b)
		z[3], b = bits.Sub64(z[3], 3528214618953670924, b)
		z[4], b = bits.Sub64(z[4], 7206257926599825404, b)
		z[5], b = bits.Sub64(z[5], 5159858282989125618, b)
		z[6], b = bits.Sub64(z[6], 4277310149175820203, b)
		z[7], b = bits.Sub64(z[7], 2252378430875190398, b)
		z[8], b = bits.Sub64(z[8], 2933629967605268401, b)
		z[9], _ = bits.Sub64(z[9], 64680000015521443, b)
	}
}

func _doubleGeneric(z, x *e_nocarry_0632) {
	var carry uint64

	z[0], carry = bits.Add64(x[0], x[0], 0)
	z[1], carry = bits.Add64(x[1], x[1], carry)
	z[2], carry = bits.Add64(x[2], x[2], carry)
	z[3], carry = bits.Add64(x[3], x[3], carry)
	z[4], carry = bits.Add64(x[4], x[4], carry)
	z[5], carry = bits.Add64(x[5], x[5], carry)
	z[6], carry = bits.Add64(x[6], x[6], carry)
	z[7], carry = bits.Add64(x[7], x[7], carry)
	z[8], carry = bits.Add64(x[8], x[8], carry)
	z[9], _ = bits.Add64(x[9], x[9], carry)

	// if z > q --> z -= q
	// note: this is NOT constant time
	if !(z[9] < 64680000015521443 || (z[9] == 64680000015521443 && (z[8] < 2933629967605268401 || (z[8] == 2933629967605268401 && (z[7] < 2252378430875190398 || (z[7] == 2252378430875190398 && (z[6] < 4277310149175820203 || (z[6] == 4277310149175820203 && (z[5] < 5159858282989125618 || (z[5] == 5159858282989125618 && (z[4] < 7206257926599825404 || (z[4] == 7206257926599825404 && (z[3] < 3528214618953670924 || (z[3] == 3528214618953670924 && (z[2] < 14536823245358974728 || (z[2] == 14536823245358974728 && (z[1] < 6387843321064356065 || (z[1] == 6387843321064356065 && (z[0] < 816069973256538473))))))))))))))))))) {
		var b uint64
		z[0], b = bits.Sub64(z[0], 816069973256538473, 0)
		z[1], b = bits.Sub64(z[1], 6387843321064356065, b)
		z[2], b = bits.Sub64(z[2], 14536823245358974728, b)
		z[3], b = bits.Sub64(z[3], 3528214618953670924, b)
		z[4], b = bits.Sub64(z[4], 7206257926599825404, b)
		z[5], b = bits.Sub64(z[5], 5159858282989125618, b)
		z[6], b = bits.Sub64(z[6], 4277310149175820203, b)
		z[7], b = bits.Sub64(z[7], 2252378430875190398, b)
		z[8], b = bits.Sub64(z[8], 2933629967605268401, b)
		z[9], _ = bits.Sub64(z[9], 64680000015521443, b)
	}
}

func _subGeneric(z, x, y *e_nocarry_0632) {
	var b uint64
	z[0], b = bits.Sub64(x[0], y[0], 0)
	z[1], b = bits.Sub64(x[1], y[1], b)
	z[2], b = bits.Sub64(x[2], y[2], b)
	z[3], b = bits.Sub64(x[3], y[3], b)
	z[4], b = bits.Sub64(x[4], y[4], b)
	z[5], b = bits.Sub64(x[5], y[5], b)
	z[6], b = bits.Sub64(x[6], y[6], b)
	z[7], b = bits.Sub64(x[7], y[7], b)
	z[8], b = bits.Sub64(x[8], y[8], b)
	z[9], b = bits.Sub64(x[9], y[9], b)
	if b != 0 {
		var c uint64
		z[0], c = bits.Add64(z[0], 816069973256538473, 0)
		z[1], c = bits.Add64(z[1], 6387843321064356065, c)
		z[2], c = bits.Add64(z[2], 14536823245358974728, c)
		z[3], c = bits.Add64(z[3], 3528214618953670924, c)
		z[4], c = bits.Add64(z[4], 7206257926599825404, c)
		z[5], c = bits.Add64(z[5], 5159858282989125618, c)
		z[6], c = bits.Add64(z[6], 4277310149175820203, c)
		z[7], c = bits.Add64(z[7], 2252378430875190398, c)
		z[8], c = bits.Add64(z[8], 2933629967605268401, c)
		z[9], _ = bits.Add64(z[9], 64680000015521443, c)
	}
}

func _negGeneric(z, x *e_nocarry_0632) {
	if x.IsZero() {
		z.SetZero()
		return
	}
	var borrow uint64
	z[0], borrow = bits.Sub64(816069973256538473, x[0], 0)
	z[1], borrow = bits.Sub64(6387843321064356065, x[1], borrow)
	z[2], borrow = bits.Sub64(14536823245358974728, x[2], borrow)
	z[3], borrow = bits.Sub64(3528214618953670924, x[3], borrow)
	z[4], borrow = bits.Sub64(7206257926599825404, x[4], borrow)
	z[5], borrow = bits.Sub64(5159858282989125618, x[5], borrow)
	z[6], borrow = bits.Sub64(4277310149175820203, x[6], borrow)
	z[7], borrow = bits.Sub64(2252378430875190398, x[7], borrow)
	z[8], borrow = bits.Sub64(2933629967605268401, x[8], borrow)
	z[9], _ = bits.Sub64(64680000015521443, x[9], borrow)
}

func _reduceGeneric(z *e_nocarry_0632) {

	// if z > q --> z -= q
	// note: this is NOT constant time
	if !(z[9] < 64680000015521443 || (z[9] == 64680000015521443 && (z[8] < 2933629967605268401 || (z[8] == 2933629967605268401 && (z[7] < 2252378430875190398 || (z[7] == 2252378430875190398 && (z[6] < 4277310149175820203 || (z[6] == 4277310149175820203 && (z[5] < 5159858282989125618 || (z[5] == 5159858282989125618 && (z[4] < 7206257926599825404 || (z[4] == 7206257926599825404 && (z[3] < 3528214618953670924 || (z[3] == 3528214618953670924 && (z[2] < 14536823245358974728 || (z[2] == 14536823245358974728 && (z[1] < 6387843321064356065 || (z[1] == 6387843321064356065 && (z[0] < 816069973256538473))))))))))))))))))) {
		var b uint64
		z[0], b = bits.Sub64(z[0], 816069973256538473, 0)
		z[1], b = bits.Sub64(z[1], 6387843321064356065, b)
		z[2], b = bits.Sub64(z[2], 14536823245358974728, b)
		z[3], b = bits.Sub64(z[3], 3528214618953670924, b)
		z[4], b = bits.Sub64(z[4], 7206257926599825404, b)
		z[5], b = bits.Sub64(z[5], 5159858282989125618, b)
		z[6], b = bits.Sub64(z[6], 4277310149175820203, b)
		z[7], b = bits.Sub64(z[7], 2252378430875190398, b)
		z[8], b = bits.Sub64(z[8], 2933629967605268401, b)
		z[9], _ = bits.Sub64(z[9], 64680000015521443, b)
	}
}

func mulByConstant(z *e_nocarry_0632, c uint8) {
	switch c {
	case 0:
		z.SetZero()
		return
	case 1:
		return
	case 2:
		z.Double(z)
		return
	case 3:
		_z := *z
		z.Double(z).Add(z, &_z)
	case 5:
		_z := *z
		z.Double(z).Double(z).Add(z, &_z)
	default:
		var y e_nocarry_0632
		y.SetUint64(uint64(c))
		z.Mul(z, &y)
	}
}

// BatchInvert returns a new slice with every element inverted.
// Uses Montgomery batch inversion trick
func BatchInvert(a []e_nocarry_0632) []e_nocarry_0632 {
	res := make([]e_nocarry_0632, len(a))
	if len(a) == 0 {
		return res
	}

	zeroes := make([]bool, len(a))
	accumulator := One()

	for i := 0; i < len(a); i++ {
		if a[i].IsZero() {
			zeroes[i] = true
			continue
		}
		res[i] = accumulator
		accumulator.Mul(&accumulator, &a[i])
	}

	accumulator.Inverse(&accumulator)

	for i := len(a) - 1; i >= 0; i-- {
		if zeroes[i] {
			continue
		}
		res[i].Mul(&res[i], &accumulator)
		accumulator.Mul(&accumulator, &a[i])
	}

	return res
}

func _butterflyGeneric(a, b *e_nocarry_0632) {
	t := *a
	a.Add(a, b)
	b.Sub(&t, b)
}

// BitLen returns the minimum number of bits needed to represent z
// returns 0 if z == 0
func (z *e_nocarry_0632) BitLen() int {
	if z[9] != 0 {
		return 576 + bits.Len64(z[9])
	}
	if z[8] != 0 {
		return 512 + bits.Len64(z[8])
	}
	if z[7] != 0 {
		return 448 + bits.Len64(z[7])
	}
	if z[6] != 0 {
		return 384 + bits.Len64(z[6])
	}
	if z[5] != 0 {
		return 320 + bits.Len64(z[5])
	}
	if z[4] != 0 {
		return 256 + bits.Len64(z[4])
	}
	if z[3] != 0 {
		return 192 + bits.Len64(z[3])
	}
	if z[2] != 0 {
		return 128 + bits.Len64(z[2])
	}
	if z[1] != 0 {
		return 64 + bits.Len64(z[1])
	}
	return bits.Len64(z[0])
}

// Exp z = x^exponent mod q
func (z *e_nocarry_0632) Exp(x e_nocarry_0632, exponent *big.Int) *e_nocarry_0632 {
	var bZero big.Int
	if exponent.Cmp(&bZero) == 0 {
		return z.SetOne()
	}

	z.Set(&x)

	for i := exponent.BitLen() - 2; i >= 0; i-- {
		z.Square(z)
		if exponent.Bit(i) == 1 {
			z.Mul(z, &x)
		}
	}

	return z
}

// ToMont converts z to Montgomery form
// sets and returns z = z * r^2
func (z *e_nocarry_0632) ToMont() *e_nocarry_0632 {
	return z.Mul(z, &rSquare)
}

// ToRegular returns z in regular form (doesn't mutate z)
func (z e_nocarry_0632) ToRegular() e_nocarry_0632 {
	return *z.FromMont()
}

// String returns the string form of an e_nocarry_0632 in Montgomery form
func (z *e_nocarry_0632) String() string {
	zz := *z
	zz.FromMont()
	if zz.IsUint64() {
		return strconv.FormatUint(zz[0], 10)
	} else {
		var zzNeg e_nocarry_0632
		zzNeg.Neg(z)
		zzNeg.FromMont()
		if zzNeg.IsUint64() {
			return "-" + strconv.FormatUint(zzNeg[0], 10)
		}
	}
	vv := bigIntPool.Get().(*big.Int)
	defer bigIntPool.Put(vv)
	return zz.ToBigInt(vv).String()
}

// ToBigInt returns z as a big.Int in Montgomery form
func (z *e_nocarry_0632) ToBigInt(res *big.Int) *big.Int {
	var b [Limbs * 8]byte
	binary.BigEndian.PutUint64(b[72:80], z[0])
	binary.BigEndian.PutUint64(b[64:72], z[1])
	binary.BigEndian.PutUint64(b[56:64], z[2])
	binary.BigEndian.PutUint64(b[48:56], z[3])
	binary.BigEndian.PutUint64(b[40:48], z[4])
	binary.BigEndian.PutUint64(b[32:40], z[5])
	binary.BigEndian.PutUint64(b[24:32], z[6])
	binary.BigEndian.PutUint64(b[16:24], z[7])
	binary.BigEndian.PutUint64(b[8:16], z[8])
	binary.BigEndian.PutUint64(b[0:8], z[9])

	return res.SetBytes(b[:])
}

// ToBigIntRegular returns z as a big.Int in regular form
func (z e_nocarry_0632) ToBigIntRegular(res *big.Int) *big.Int {
	z.FromMont()
	return z.ToBigInt(res)
}

// Bytes returns the regular (non montgomery) value
// of z as a big-endian byte array.
func (z *e_nocarry_0632) Bytes() (res [Limbs * 8]byte) {
	_z := z.ToRegular()
	binary.BigEndian.PutUint64(res[72:80], _z[0])
	binary.BigEndian.PutUint64(res[64:72], _z[1])
	binary.BigEndian.PutUint64(res[56:64], _z[2])
	binary.BigEndian.PutUint64(res[48:56], _z[3])
	binary.BigEndian.PutUint64(res[40:48], _z[4])
	binary.BigEndian.PutUint64(res[32:40], _z[5])
	binary.BigEndian.PutUint64(res[24:32], _z[6])
	binary.BigEndian.PutUint64(res[16:24], _z[7])
	binary.BigEndian.PutUint64(res[8:16], _z[8])
	binary.BigEndian.PutUint64(res[0:8], _z[9])

	return
}

// Marshal returns the regular (non montgomery) value
// of z as a big-endian byte slice.
func (z *e_nocarry_0632) Marshal() []byte {
	b := z.Bytes()
	return b[:]
}

// SetBytes interprets e as the bytes of a big-endian unsigned integer,
// sets z to that value (in Montgomery form), and returns z.
func (z *e_nocarry_0632) SetBytes(e []byte) *e_nocarry_0632 {
	// get a big int from our pool
	vv := bigIntPool.Get().(*big.Int)
	vv.SetBytes(e)

	// set big int
	z.SetBigInt(vv)

	// put temporary object back in pool
	bigIntPool.Put(vv)

	return z
}

// SetBigInt sets z to v (regular form) and returns z in Montgomery form
func (z *e_nocarry_0632) SetBigInt(v *big.Int) *e_nocarry_0632 {
	z.SetZero()

	var zero big.Int

	// fast path
	c := v.Cmp(&_modulus)
	if c == 0 {
		// v == 0
		return z
	} else if c != 1 && v.Cmp(&zero) != -1 {
		// 0 < v < q
		return z.setBigInt(v)
	}

	// get temporary big int from the pool
	vv := bigIntPool.Get().(*big.Int)

	// copy input + modular reduction
	vv.Set(v)
	vv.Mod(v, &_modulus)

	// set big int byte value
	z.setBigInt(vv)

	// release object into pool
	bigIntPool.Put(vv)
	return z
}

// setBigInt assumes 0 <= v < q
func (z *e_nocarry_0632) setBigInt(v *big.Int) *e_nocarry_0632 {
	vBits := v.Bits()

	if bits.UintSize == 64 {
		for i := 0; i < len(vBits); i++ {
			z[i] = uint64(vBits[i])
		}
	} else {
		for i := 0; i < len(vBits); i++ {
			if i%2 == 0 {
				z[i/2] = uint64(vBits[i])
			} else {
				z[i/2] |= uint64(vBits[i]) << 32
			}
		}
	}

	return z.ToMont()
}

// SetString creates a big.Int with s (in base 10) and calls SetBigInt on z
func (z *e_nocarry_0632) SetString(s string) *e_nocarry_0632 {
	// get temporary big int from the pool
	vv := bigIntPool.Get().(*big.Int)

	if _, ok := vv.SetString(s, 10); !ok {
		panic("e_nocarry_0632.SetString failed -> can't parse number in base10 into a big.Int")
	}
	z.SetBigInt(vv)

	// release object into pool
	bigIntPool.Put(vv)

	return z
}

var (
	_bLegendreExponente_nocarry_0632 *big.Int
	_bSqrtExponente_nocarry_0632     *big.Int
)

func init() {
	_bLegendreExponente_nocarry_0632, _ = new(big.Int).SetString("72e50f047fab51945b2c74ccc6bfd88fa1071fe808a23f1dae077591e61fd5a3cdbfe298763ff93200e2b3b169abfe187b5e405709708664de95dc7321a3842c5316d400723c7085a9a1a891e8c4b4", 16)
	const sqrtExponente_nocarry_0632 = "e5ca1e08ff56a328b658e9998d7fb11f420e3fd011447e3b5c0eeb23cc3fab479b7fc530ec7ff26401c56762d357fc30f6bc80ae12e10cc9bd2bb8e643470858a62da800e478e10b53435123d1896"
	_bSqrtExponente_nocarry_0632, _ = new(big.Int).SetString(sqrtExponente_nocarry_0632, 16)
}

// Legendre returns the Legendre symbol of z (either +1, -1, or 0.)
func (z *e_nocarry_0632) Legendre() int {
	var l e_nocarry_0632
	// z^((q-1)/2)
	l.Exp(*z, _bLegendreExponente_nocarry_0632)

	if l.IsZero() {
		return 0
	}

	// if l == 1
	if (l[9] == 12944069285940315) && (l[8] == 12465686623137880016) && (l[7] == 3708189780405043063) && (l[6] == 16898460423431200337) && (l[5] == 5179915244863328038) && (l[4] == 12251827174519540797) && (l[3] == 9029757652229125315) && (l[2] == 7522791657341316021) && (l[1] == 5692316793904131446) && (l[0] == 7227730580110706203) {
		return 1
	}
	return -1
}

// Sqrt z = √x mod q
// if the square root doesn't exist (x is not a square mod q)
// Sqrt leaves z unchanged and returns nil
func (z *e_nocarry_0632) Sqrt(x *e_nocarry_0632) *e_nocarry_0632 {
	// q ≡ 1 (mod 4)
	// see modSqrtTonelliShanks in math/big/int.go
	// using https://www.maa.org/sites/default/files/pdf/upload_library/22/Polya/07468342.di020786.02p0470a.pdf

	var y, b, t, w e_nocarry_0632
	// w = x^((s-1)/2))
	w.Exp(*x, _bSqrtExponente_nocarry_0632)

	// y = x^((s+1)/2)) = w * x
	y.Mul(x, &w)

	// b = x^s = w * w * x = y * x
	b.Mul(&w, &y)

	// g = nonResidue ^ s
	var g = e_nocarry_0632{
		6407354675631511314,
		11908118533129377069,
		13259287144813787192,
		3438937907290890055,
		16631971669247878935,
		3360518686521413321,
		8484543580322450956,
		1198685850728364843,
		11964502799005750299,
		40112111383030155,
	}
	r := uint64(3)

	// compute legendre symbol
	// t = x^((q-1)/2) = r-1 squaring of x^s
	t = b
	for i := uint64(0); i < r-1; i++ {
		t.Square(&t)
	}
	if t.IsZero() {
		return z.SetZero()
	}
	if !((t[9] == 12944069285940315) && (t[8] == 12465686623137880016) && (t[7] == 3708189780405043063) && (t[6] == 16898460423431200337) && (t[5] == 5179915244863328038) && (t[4] == 12251827174519540797) && (t[3] == 9029757652229125315) && (t[2] == 7522791657341316021) && (t[1] == 5692316793904131446) && (t[0] == 7227730580110706203)) {
		// t != 1, we don't have a square root
		return nil
	}
	for {
		var m uint64
		t = b

		// for t != 1
		for !((t[9] == 12944069285940315) && (t[8] == 12465686623137880016) && (t[7] == 3708189780405043063) && (t[6] == 16898460423431200337) && (t[5] == 5179915244863328038) && (t[4] == 12251827174519540797) && (t[3] == 9029757652229125315) && (t[2] == 7522791657341316021) && (t[1] == 5692316793904131446) && (t[0] == 7227730580110706203)) {
			t.Square(&t)
			m++
		}

		if m == 0 {
			return z.Set(&y)
		}
		// t = g^(2^(r-m-1)) mod q
		ge := int(r - m - 1)
		t = g
		for ge > 0 {
			t.Square(&t)
			ge--
		}

		g.Square(&t)
		y.Mul(&y, &t)
		b.Mul(&b, &g)
		r = m
	}
}

// Inverse z = x^-1 mod q
// Algorithm 16 in "Efficient Software-Implementation of Finite Fields with Applications to Cryptography"
// if x == 0, sets and returns z = x
func (z *e_nocarry_0632) InverseOld(x *e_nocarry_0632) *e_nocarry_0632 {
	if x.IsZero() {
		z.SetZero()
		return z
	}

	// initialize u = q
	var u = e_nocarry_0632{
		816069973256538473,
		6387843321064356065,
		14536823245358974728,
		3528214618953670924,
		7206257926599825404,
		5159858282989125618,
		4277310149175820203,
		2252378430875190398,
		2933629967605268401,
		64680000015521443,
	}

	// initialize s = r^2
	var s = e_nocarry_0632{
		14095748637358075099,
		14972327332075549804,
		7361626879976866655,
		11832497490297147285,
		12761415501496589237,
		6643493509961268799,
		16277603966381323758,
		4172976593577508314,
		11557828093366462360,
		35540955938236791,
	}

	// r = 0
	r := e_nocarry_0632{}

	v := *x

	var carry, borrow uint64
	var bigger bool

	for {
		for v[0]&1 == 0 {

			// v = v >> 1

			v[0] = v[0]>>1 | v[1]<<63
			v[1] = v[1]>>1 | v[2]<<63
			v[2] = v[2]>>1 | v[3]<<63
			v[3] = v[3]>>1 | v[4]<<63
			v[4] = v[4]>>1 | v[5]<<63
			v[5] = v[5]>>1 | v[6]<<63
			v[6] = v[6]>>1 | v[7]<<63
			v[7] = v[7]>>1 | v[8]<<63
			v[8] = v[8]>>1 | v[9]<<63
			v[9] >>= 1

			if s[0]&1 == 1 {

				// s = s + q
				s[0], carry = bits.Add64(s[0], 816069973256538473, 0)
				s[1], carry = bits.Add64(s[1], 6387843321064356065, carry)
				s[2], carry = bits.Add64(s[2], 14536823245358974728, carry)
				s[3], carry = bits.Add64(s[3], 3528214618953670924, carry)
				s[4], carry = bits.Add64(s[4], 7206257926599825404, carry)
				s[5], carry = bits.Add64(s[5], 5159858282989125618, carry)
				s[6], carry = bits.Add64(s[6], 4277310149175820203, carry)
				s[7], carry = bits.Add64(s[7], 2252378430875190398, carry)
				s[8], carry = bits.Add64(s[8], 2933629967605268401, carry)
				s[9], _ = bits.Add64(s[9], 64680000015521443, carry)

			}

			// s = s >> 1

			s[0] = s[0]>>1 | s[1]<<63
			s[1] = s[1]>>1 | s[2]<<63
			s[2] = s[2]>>1 | s[3]<<63
			s[3] = s[3]>>1 | s[4]<<63
			s[4] = s[4]>>1 | s[5]<<63
			s[5] = s[5]>>1 | s[6]<<63
			s[6] = s[6]>>1 | s[7]<<63
			s[7] = s[7]>>1 | s[8]<<63
			s[8] = s[8]>>1 | s[9]<<63
			s[9] >>= 1

		}
		for u[0]&1 == 0 {

			// u = u >> 1

			u[0] = u[0]>>1 | u[1]<<63
			u[1] = u[1]>>1 | u[2]<<63
			u[2] = u[2]>>1 | u[3]<<63
			u[3] = u[3]>>1 | u[4]<<63
			u[4] = u[4]>>1 | u[5]<<63
			u[5] = u[5]>>1 | u[6]<<63
			u[6] = u[6]>>1 | u[7]<<63
			u[7] = u[7]>>1 | u[8]<<63
			u[8] = u[8]>>1 | u[9]<<63
			u[9] >>= 1

			if r[0]&1 == 1 {

				// r = r + q
				r[0], carry = bits.Add64(r[0], 816069973256538473, 0)
				r[1], carry = bits.Add64(r[1], 6387843321064356065, carry)
				r[2], carry = bits.Add64(r[2], 14536823245358974728, carry)
				r[3], carry = bits.Add64(r[3], 3528214618953670924, carry)
				r[4], carry = bits.Add64(r[4], 7206257926599825404, carry)
				r[5], carry = bits.Add64(r[5], 5159858282989125618, carry)
				r[6], carry = bits.Add64(r[6], 4277310149175820203, carry)
				r[7], carry = bits.Add64(r[7], 2252378430875190398, carry)
				r[8], carry = bits.Add64(r[8], 2933629967605268401, carry)
				r[9], _ = bits.Add64(r[9], 64680000015521443, carry)

			}

			// r = r >> 1

			r[0] = r[0]>>1 | r[1]<<63
			r[1] = r[1]>>1 | r[2]<<63
			r[2] = r[2]>>1 | r[3]<<63
			r[3] = r[3]>>1 | r[4]<<63
			r[4] = r[4]>>1 | r[5]<<63
			r[5] = r[5]>>1 | r[6]<<63
			r[6] = r[6]>>1 | r[7]<<63
			r[7] = r[7]>>1 | r[8]<<63
			r[8] = r[8]>>1 | r[9]<<63
			r[9] >>= 1

		}

		// v >= u
		bigger = !(v[9] < u[9] || (v[9] == u[9] && (v[8] < u[8] || (v[8] == u[8] && (v[7] < u[7] || (v[7] == u[7] && (v[6] < u[6] || (v[6] == u[6] && (v[5] < u[5] || (v[5] == u[5] && (v[4] < u[4] || (v[4] == u[4] && (v[3] < u[3] || (v[3] == u[3] && (v[2] < u[2] || (v[2] == u[2] && (v[1] < u[1] || (v[1] == u[1] && (v[0] < u[0])))))))))))))))))))

		if bigger {

			// v = v - u
			v[0], borrow = bits.Sub64(v[0], u[0], 0)
			v[1], borrow = bits.Sub64(v[1], u[1], borrow)
			v[2], borrow = bits.Sub64(v[2], u[2], borrow)
			v[3], borrow = bits.Sub64(v[3], u[3], borrow)
			v[4], borrow = bits.Sub64(v[4], u[4], borrow)
			v[5], borrow = bits.Sub64(v[5], u[5], borrow)
			v[6], borrow = bits.Sub64(v[6], u[6], borrow)
			v[7], borrow = bits.Sub64(v[7], u[7], borrow)
			v[8], borrow = bits.Sub64(v[8], u[8], borrow)
			v[9], _ = bits.Sub64(v[9], u[9], borrow)

			// s = s - r
			s[0], borrow = bits.Sub64(s[0], r[0], 0)
			s[1], borrow = bits.Sub64(s[1], r[1], borrow)
			s[2], borrow = bits.Sub64(s[2], r[2], borrow)
			s[3], borrow = bits.Sub64(s[3], r[3], borrow)
			s[4], borrow = bits.Sub64(s[4], r[4], borrow)
			s[5], borrow = bits.Sub64(s[5], r[5], borrow)
			s[6], borrow = bits.Sub64(s[6], r[6], borrow)
			s[7], borrow = bits.Sub64(s[7], r[7], borrow)
			s[8], borrow = bits.Sub64(s[8], r[8], borrow)
			s[9], borrow = bits.Sub64(s[9], r[9], borrow)

			if borrow == 1 {

				// s = s + q
				s[0], carry = bits.Add64(s[0], 816069973256538473, 0)
				s[1], carry = bits.Add64(s[1], 6387843321064356065, carry)
				s[2], carry = bits.Add64(s[2], 14536823245358974728, carry)
				s[3], carry = bits.Add64(s[3], 3528214618953670924, carry)
				s[4], carry = bits.Add64(s[4], 7206257926599825404, carry)
				s[5], carry = bits.Add64(s[5], 5159858282989125618, carry)
				s[6], carry = bits.Add64(s[6], 4277310149175820203, carry)
				s[7], carry = bits.Add64(s[7], 2252378430875190398, carry)
				s[8], carry = bits.Add64(s[8], 2933629967605268401, carry)
				s[9], _ = bits.Add64(s[9], 64680000015521443, carry)

			}
		} else {

			// u = u - v
			u[0], borrow = bits.Sub64(u[0], v[0], 0)
			u[1], borrow = bits.Sub64(u[1], v[1], borrow)
			u[2], borrow = bits.Sub64(u[2], v[2], borrow)
			u[3], borrow = bits.Sub64(u[3], v[3], borrow)
			u[4], borrow = bits.Sub64(u[4], v[4], borrow)
			u[5], borrow = bits.Sub64(u[5], v[5], borrow)
			u[6], borrow = bits.Sub64(u[6], v[6], borrow)
			u[7], borrow = bits.Sub64(u[7], v[7], borrow)
			u[8], borrow = bits.Sub64(u[8], v[8], borrow)
			u[9], _ = bits.Sub64(u[9], v[9], borrow)

			// r = r - s
			r[0], borrow = bits.Sub64(r[0], s[0], 0)
			r[1], borrow = bits.Sub64(r[1], s[1], borrow)
			r[2], borrow = bits.Sub64(r[2], s[2], borrow)
			r[3], borrow = bits.Sub64(r[3], s[3], borrow)
			r[4], borrow = bits.Sub64(r[4], s[4], borrow)
			r[5], borrow = bits.Sub64(r[5], s[5], borrow)
			r[6], borrow = bits.Sub64(r[6], s[6], borrow)
			r[7], borrow = bits.Sub64(r[7], s[7], borrow)
			r[8], borrow = bits.Sub64(r[8], s[8], borrow)
			r[9], borrow = bits.Sub64(r[9], s[9], borrow)

			if borrow == 1 {

				// r = r + q
				r[0], carry = bits.Add64(r[0], 816069973256538473, 0)
				r[1], carry = bits.Add64(r[1], 6387843321064356065, carry)
				r[2], carry = bits.Add64(r[2], 14536823245358974728, carry)
				r[3], carry = bits.Add64(r[3], 3528214618953670924, carry)
				r[4], carry = bits.Add64(r[4], 7206257926599825404, carry)
				r[5], carry = bits.Add64(r[5], 5159858282989125618, carry)
				r[6], carry = bits.Add64(r[6], 4277310149175820203, carry)
				r[7], carry = bits.Add64(r[7], 2252378430875190398, carry)
				r[8], carry = bits.Add64(r[8], 2933629967605268401, carry)
				r[9], _ = bits.Add64(r[9], 64680000015521443, carry)

			}
		}
		if (u[0] == 1) && (u[9]|u[8]|u[7]|u[6]|u[5]|u[4]|u[3]|u[2]|u[1]) == 0 {
			z.Set(&r)
			return z
		}
		if (v[0] == 1) && (v[9]|v[8]|v[7]|v[6]|v[5]|v[4]|v[3]|v[2]|v[1]) == 0 {
			z.Set(&s)
			return z
		}
	}

}

func max(a int, b int) int {
	if a > b {
		return a
	}
	return b
}

func min(a int, b int) int {
	if a < b {
		return a
	}
	return b
}

//Though we're defining k as a constant, this code "profoundly" assumes that the processor is 64 bit
const k = 32 // word size / 2
const signBitSelector = uint64(1) << 63
const approxLowBitsN = k - 1
const approxHighBitsN = k + 1

func approximate(x *e_nocarry_0632, n int) uint64 {

	if n <= 64 {
		return x[0]
	}

	const mask = (uint64(1) << (k - 1)) - 1 //k-1 ones
	lo := mask & x[0]

	hiWordIndex := (n - 1) / 64

	hiWordBitsAvailable := n - hiWordIndex*64
	hiWordBitsUsed := min(hiWordBitsAvailable, approxHighBitsN)

	mask_ := uint64(^((1 << (hiWordBitsAvailable - hiWordBitsUsed)) - 1))
	hi := (x[hiWordIndex] & mask_) << (64 - hiWordBitsAvailable)

	mask_ = ^(1<<(approxLowBitsN+hiWordBitsUsed) - 1)
	mid := (mask_ & x[hiWordIndex-1]) >> hiWordBitsUsed

	return lo | mid | hi
}

var inversionCorrectionFactor = e_nocarry_0632{
	12097903364306348573,
	7435551273531104660,
	3388661384417594310,
	9583136260229716135,
	5988104380994135966,
	14777203831051237505,
	16407563747850898613,
	1424718690892496750,
	14146846856407711188,
	53623479988562715,
}

func (z *e_nocarry_0632) Inverse(x *e_nocarry_0632) *e_nocarry_0632 {
	if x.IsZero() {
		z.SetZero()
		return z
	}

	var a = *x
	var b = qe_nocarry_0632
	var u = e_nocarry_0632{1}

	//Update factors: we get [u; v]:= [f0 g0; f1 g1] [u; v]
	var f0, g0, f1, g1 int64

	//Saved update factors to reduce the number of field multiplications
	var pf0, pg0, pf1, pg1 int64

	var i uint

	var v, s e_nocarry_0632

	const iterationN = 2 * ((2*Bits-2)/(2*k) + 1) // 2  ⌈ (2 * field size - 1) / 2k ⌉

	//Since u,v are updated every other iteration, we must make sure we terminate after evenly many iterations
	//This also lets us get away with half as many updates to u,v
	//To make this constant-time-ish, replace the condition with i < iterationN
	for i = 0; i&1 == 1 || !a.IsZero(); i++ {
		n := max(a.BitLen(), b.BitLen())
		aApprox, bApprox := approximate(&a, n), approximate(&b, n)

		// After 0 iterations, we have f₀ ≤ 2⁰ and f₁ < 2⁰
		f0, g0, f1, g1 = 1, 0, 0, 1

		for j := 0; j < approxLowBitsN; j++ {

			if aApprox&1 == 0 {
				aApprox /= 2
			} else {
				s, borrow := bits.Sub64(aApprox, bApprox, 0)
				if borrow == 1 {
					s = bApprox - aApprox
					bApprox = aApprox
					f0, f1 = f1, f0
					g0, g1 = g1, g0
				}

				aApprox = s / 2
				f0 -= f1
				g0 -= g1

				//Now |f₀| < 2ʲ + 2ʲ = 2ʲ⁺¹
				//|f₁| ≤ 2ʲ still
			}

			f1 *= 2
			g1 *= 2
			//|f₁| ≤ 2ʲ⁺¹
		}

		s = a
		aHi := a.linearCombNonModular(&s, f0, &b, g0)
		if aHi&signBitSelector != 0 {
			// if aHi < 0
			f0, g0 = -f0, -g0
			aHi = a.neg(&a, aHi)
		}
		//right-shift a by k-1 bits
		a[0] = (a[0] >> approxLowBitsN) | ((a[1]) << approxHighBitsN)
		a[1] = (a[1] >> approxLowBitsN) | ((a[2]) << approxHighBitsN)
		a[2] = (a[2] >> approxLowBitsN) | ((a[3]) << approxHighBitsN)
		a[3] = (a[3] >> approxLowBitsN) | ((a[4]) << approxHighBitsN)
		a[4] = (a[4] >> approxLowBitsN) | ((a[5]) << approxHighBitsN)
		a[5] = (a[5] >> approxLowBitsN) | ((a[6]) << approxHighBitsN)
		a[6] = (a[6] >> approxLowBitsN) | ((a[7]) << approxHighBitsN)
		a[7] = (a[7] >> approxLowBitsN) | ((a[8]) << approxHighBitsN)
		a[8] = (a[8] >> approxLowBitsN) | ((a[9]) << approxHighBitsN)
		a[9] = (a[9] >> approxLowBitsN) | (aHi << approxHighBitsN)

		bHi := b.linearCombNonModular(&s, f1, &b, g1)
		if bHi&signBitSelector != 0 {
			// if bHi < 0
			f1, g1 = -f1, -g1
			bHi = b.neg(&b, bHi)
		}
		//right-shift b by k-1 bits
		b[0] = (b[0] >> approxLowBitsN) | ((b[1]) << approxHighBitsN)
		b[1] = (b[1] >> approxLowBitsN) | ((b[2]) << approxHighBitsN)
		b[2] = (b[2] >> approxLowBitsN) | ((b[3]) << approxHighBitsN)
		b[3] = (b[3] >> approxLowBitsN) | ((b[4]) << approxHighBitsN)
		b[4] = (b[4] >> approxLowBitsN) | ((b[5]) << approxHighBitsN)
		b[5] = (b[5] >> approxLowBitsN) | ((b[6]) << approxHighBitsN)
		b[6] = (b[6] >> approxLowBitsN) | ((b[7]) << approxHighBitsN)
		b[7] = (b[7] >> approxLowBitsN) | ((b[8]) << approxHighBitsN)
		b[8] = (b[8] >> approxLowBitsN) | ((b[9]) << approxHighBitsN)
		b[9] = (b[9] >> approxLowBitsN) | (bHi << approxHighBitsN)

		if i&1 == 1 {
			//Combine current update factors with previously stored ones
			// [f₀, g₀; f₁, g₁] ← [f₀, g₀; f₁, g₀] [pf₀, pg₀; pf₀, pg₀]
			// We have |f₀|, |g₀|, |pf₀|, |pf₁| ≤ 2ᵏ⁻¹, and that |pf_i| < 2ᵏ⁻¹ for i ∈ {0, 1}
			// Then for the new value we get |f₀| < 2ᵏ⁻¹ × 2ᵏ⁻¹ + 2ᵏ⁻¹ × 2ᵏ⁻¹ = 2²ᵏ⁻¹
			// Which leaves us with an extra bit for the sign
			f0, g0, f1, g1 = f0*pf0+g0*pf1,
				f0*pg0+g0*pg1,
				f1*pf0+g1*pf1,
				f1*pg0+g1*pg1

			s = u
			u.linearCombSosSigned(&u, f0, &v, g0)
			v.linearCombSosSigned(&s, f1, &v, g1)

		} else {
			//Save update factors
			pf0, pg0, pf1, pg1 = f0, g0, f1, g1
		}
	}

	if i > iterationN {
		panic("more iterations than expected")
	}

	//For every iteration that we miss, v is not being multiplied by 2²ᵏ⁻²
	const pSq int64 = 1 << (2 * (k - 1))
	//If the function is constant-time ish, this loop will not run (probably no need to take it out explicitly)
	for ; i < iterationN; i += 2 {
		v.mulWSigned(&v, pSq)
	}

	z.Mul(&v, &inversionCorrectionFactor)
	return z
}

func (z *e_nocarry_0632) linearCombSosSigned(x *e_nocarry_0632, xC int64, y *e_nocarry_0632, yC int64) {
	hi := z.linearCombNonModular(x, xC, y, yC)
	z.montReduceSigned(z, hi)
}

//montReduceSigned SOS algorithm; xHi must be at most 63 bits long. Last bit of xHi may be used as a sign bit
func (z *e_nocarry_0632) montReduceSigned(x *e_nocarry_0632, xHi uint64) {

	const qInvNegLsw uint64 = 3770451588057426215
	const signBitRemover = ^signBitSelector
	neg := xHi&signBitSelector != 0
	//the SOS implementation requires that most significant bit is 0
	// Let X be xHi*r + x
	// note that if X is negative we would have initially stored it as 2⁶⁴ r + X
	xHi &= signBitRemover
	// with this a negative X is now represented as 2⁶³ r + X

	var t [2*Limbs - 1]uint64
	var C uint64

	m := x[0] * qInvNegLsw

	C = madd0(m, qe_nocarry_0632[0], x[0])
	C, t[1] = madd2(m, qe_nocarry_0632[1], x[1], C)
	C, t[2] = madd2(m, qe_nocarry_0632[2], x[2], C)
	C, t[3] = madd2(m, qe_nocarry_0632[3], x[3], C)
	C, t[4] = madd2(m, qe_nocarry_0632[4], x[4], C)
	C, t[5] = madd2(m, qe_nocarry_0632[5], x[5], C)
	C, t[6] = madd2(m, qe_nocarry_0632[6], x[6], C)
	C, t[7] = madd2(m, qe_nocarry_0632[7], x[7], C)
	C, t[8] = madd2(m, qe_nocarry_0632[8], x[8], C)
	C, t[9] = madd2(m, qe_nocarry_0632[9], x[9], C)

	// the high word of m * qe_nocarry_0632[9] is at most 62 bits
	// x[9] + C is at most 65 bits (high word at most 1 bit)
	// Thus the resulting C will be at most 63 bits
	t[10] = xHi + C
	// xHi and C are 63 bits, therefore no overflow

	{
		const i = 1
		m = t[i] * qInvNegLsw

		//TODO: Is it better to hard-code the values of qe_nocarry_0632 as the "reduce" template does?
		C = madd0(m, qe_nocarry_0632[0], t[i+0])
		C, t[i+1] = madd2(m, qe_nocarry_0632[1], t[i+1], C)
		C, t[i+2] = madd2(m, qe_nocarry_0632[2], t[i+2], C)
		C, t[i+3] = madd2(m, qe_nocarry_0632[3], t[i+3], C)
		C, t[i+4] = madd2(m, qe_nocarry_0632[4], t[i+4], C)
		C, t[i+5] = madd2(m, qe_nocarry_0632[5], t[i+5], C)
		C, t[i+6] = madd2(m, qe_nocarry_0632[6], t[i+6], C)
		C, t[i+7] = madd2(m, qe_nocarry_0632[7], t[i+7], C)
		C, t[i+8] = madd2(m, qe_nocarry_0632[8], t[i+8], C)
		C, t[i+9] = madd2(m, qe_nocarry_0632[9], t[i+9], C)

		t[i+Limbs] += C
	}
	{
		const i = 2
		m = t[i] * qInvNegLsw

		//TODO: Is it better to hard-code the values of qe_nocarry_0632 as the "reduce" template does?
		C = madd0(m, qe_nocarry_0632[0], t[i+0])
		C, t[i+1] = madd2(m, qe_nocarry_0632[1], t[i+1], C)
		C, t[i+2] = madd2(m, qe_nocarry_0632[2], t[i+2], C)
		C, t[i+3] = madd2(m, qe_nocarry_0632[3], t[i+3], C)
		C, t[i+4] = madd2(m, qe_nocarry_0632[4], t[i+4], C)
		C, t[i+5] = madd2(m, qe_nocarry_0632[5], t[i+5], C)
		C, t[i+6] = madd2(m, qe_nocarry_0632[6], t[i+6], C)
		C, t[i+7] = madd2(m, qe_nocarry_0632[7], t[i+7], C)
		C, t[i+8] = madd2(m, qe_nocarry_0632[8], t[i+8], C)
		C, t[i+9] = madd2(m, qe_nocarry_0632[9], t[i+9], C)

		t[i+Limbs] += C
	}
	{
		const i = 3
		m = t[i] * qInvNegLsw

		//TODO: Is it better to hard-code the values of qe_nocarry_0632 as the "reduce" template does?
		C = madd0(m, qe_nocarry_0632[0], t[i+0])
		C, t[i+1] = madd2(m, qe_nocarry_0632[1], t[i+1], C)
		C, t[i+2] = madd2(m, qe_nocarry_0632[2], t[i+2], C)
		C, t[i+3] = madd2(m, qe_nocarry_0632[3], t[i+3], C)
		C, t[i+4] = madd2(m, qe_nocarry_0632[4], t[i+4], C)
		C, t[i+5] = madd2(m, qe_nocarry_0632[5], t[i+5], C)
		C, t[i+6] = madd2(m, qe_nocarry_0632[6], t[i+6], C)
		C, t[i+7] = madd2(m, qe_nocarry_0632[7], t[i+7], C)
		C, t[i+8] = madd2(m, qe_nocarry_0632[8], t[i+8], C)
		C, t[i+9] = madd2(m, qe_nocarry_0632[9], t[i+9], C)

		t[i+Limbs] += C
	}
	{
		const i = 4
		m = t[i] * qInvNegLsw

		//TODO: Is it better to hard-code the values of qe_nocarry_0632 as the "reduce" template does?
		C = madd0(m, qe_nocarry_0632[0], t[i+0])
		C, t[i+1] = madd2(m, qe_nocarry_0632[1], t[i+1], C)
		C, t[i+2] = madd2(m, qe_nocarry_0632[2], t[i+2], C)
		C, t[i+3] = madd2(m, qe_nocarry_0632[3], t[i+3], C)
		C, t[i+4] = madd2(m, qe_nocarry_0632[4], t[i+4], C)
		C, t[i+5] = madd2(m, qe_nocarry_0632[5], t[i+5], C)
		C, t[i+6] = madd2(m, qe_nocarry_0632[6], t[i+6], C)
		C, t[i+7] = madd2(m, qe_nocarry_0632[7], t[i+7], C)
		C, t[i+8] = madd2(m, qe_nocarry_0632[8], t[i+8], C)
		C, t[i+9] = madd2(m, qe_nocarry_0632[9], t[i+9], C)

		t[i+Limbs] += C
	}
	{
		const i = 5
		m = t[i] * qInvNegLsw

		//TODO: Is it better to hard-code the values of qe_nocarry_0632 as the "reduce" template does?
		C = madd0(m, qe_nocarry_0632[0], t[i+0])
		C, t[i+1] = madd2(m, qe_nocarry_0632[1], t[i+1], C)
		C, t[i+2] = madd2(m, qe_nocarry_0632[2], t[i+2], C)
		C, t[i+3] = madd2(m, qe_nocarry_0632[3], t[i+3], C)
		C, t[i+4] = madd2(m, qe_nocarry_0632[4], t[i+4], C)
		C, t[i+5] = madd2(m, qe_nocarry_0632[5], t[i+5], C)
		C, t[i+6] = madd2(m, qe_nocarry_0632[6], t[i+6], C)
		C, t[i+7] = madd2(m, qe_nocarry_0632[7], t[i+7], C)
		C, t[i+8] = madd2(m, qe_nocarry_0632[8], t[i+8], C)
		C, t[i+9] = madd2(m, qe_nocarry_0632[9], t[i+9], C)

		t[i+Limbs] += C
	}
	{
		const i = 6
		m = t[i] * qInvNegLsw

		//TODO: Is it better to hard-code the values of qe_nocarry_0632 as the "reduce" template does?
		C = madd0(m, qe_nocarry_0632[0], t[i+0])
		C, t[i+1] = madd2(m, qe_nocarry_0632[1], t[i+1], C)
		C, t[i+2] = madd2(m, qe_nocarry_0632[2], t[i+2], C)
		C, t[i+3] = madd2(m, qe_nocarry_0632[3], t[i+3], C)
		C, t[i+4] = madd2(m, qe_nocarry_0632[4], t[i+4], C)
		C, t[i+5] = madd2(m, qe_nocarry_0632[5], t[i+5], C)
		C, t[i+6] = madd2(m, qe_nocarry_0632[6], t[i+6], C)
		C, t[i+7] = madd2(m, qe_nocarry_0632[7], t[i+7], C)
		C, t[i+8] = madd2(m, qe_nocarry_0632[8], t[i+8], C)
		C, t[i+9] = madd2(m, qe_nocarry_0632[9], t[i+9], C)

		t[i+Limbs] += C
	}
	{
		const i = 7
		m = t[i] * qInvNegLsw

		//TODO: Is it better to hard-code the values of qe_nocarry_0632 as the "reduce" template does?
		C = madd0(m, qe_nocarry_0632[0], t[i+0])
		C, t[i+1] = madd2(m, qe_nocarry_0632[1], t[i+1], C)
		C, t[i+2] = madd2(m, qe_nocarry_0632[2], t[i+2], C)
		C, t[i+3] = madd2(m, qe_nocarry_0632[3], t[i+3], C)
		C, t[i+4] = madd2(m, qe_nocarry_0632[4], t[i+4], C)
		C, t[i+5] = madd2(m, qe_nocarry_0632[5], t[i+5], C)
		C, t[i+6] = madd2(m, qe_nocarry_0632[6], t[i+6], C)
		C, t[i+7] = madd2(m, qe_nocarry_0632[7], t[i+7], C)
		C, t[i+8] = madd2(m, qe_nocarry_0632[8], t[i+8], C)
		C, t[i+9] = madd2(m, qe_nocarry_0632[9], t[i+9], C)

		t[i+Limbs] += C
	}
	{
		const i = 8
		m = t[i] * qInvNegLsw

		//TODO: Is it better to hard-code the values of qe_nocarry_0632 as the "reduce" template does?
		C = madd0(m, qe_nocarry_0632[0], t[i+0])
		C, t[i+1] = madd2(m, qe_nocarry_0632[1], t[i+1], C)
		C, t[i+2] = madd2(m, qe_nocarry_0632[2], t[i+2], C)
		C, t[i+3] = madd2(m, qe_nocarry_0632[3], t[i+3], C)
		C, t[i+4] = madd2(m, qe_nocarry_0632[4], t[i+4], C)
		C, t[i+5] = madd2(m, qe_nocarry_0632[5], t[i+5], C)
		C, t[i+6] = madd2(m, qe_nocarry_0632[6], t[i+6], C)
		C, t[i+7] = madd2(m, qe_nocarry_0632[7], t[i+7], C)
		C, t[i+8] = madd2(m, qe_nocarry_0632[8], t[i+8], C)
		C, t[i+9] = madd2(m, qe_nocarry_0632[9], t[i+9], C)

		t[i+Limbs] += C
	}
	{
		const i = 9
		m := t[i] * qInvNegLsw

		C = madd0(m, qe_nocarry_0632[0], t[i+0])
		C, z[0] = madd2(m, qe_nocarry_0632[1], t[i+1], C)
		C, z[1] = madd2(m, qe_nocarry_0632[2], t[i+2], C)
		C, z[2] = madd2(m, qe_nocarry_0632[3], t[i+3], C)
		C, z[3] = madd2(m, qe_nocarry_0632[4], t[i+4], C)
		C, z[4] = madd2(m, qe_nocarry_0632[5], t[i+5], C)
		C, z[5] = madd2(m, qe_nocarry_0632[6], t[i+6], C)
		C, z[6] = madd2(m, qe_nocarry_0632[7], t[i+7], C)
		C, z[7] = madd2(m, qe_nocarry_0632[8], t[i+8], C)
		z[9], z[8] = madd2(m, qe_nocarry_0632[9], t[i+9], C)
	}

	// if z > q --> z -= q
	// note: this is NOT constant time
	if !(z[9] < 64680000015521443 || (z[9] == 64680000015521443 && (z[8] < 2933629967605268401 || (z[8] == 2933629967605268401 && (z[7] < 2252378430875190398 || (z[7] == 2252378430875190398 && (z[6] < 4277310149175820203 || (z[6] == 4277310149175820203 && (z[5] < 5159858282989125618 || (z[5] == 5159858282989125618 && (z[4] < 7206257926599825404 || (z[4] == 7206257926599825404 && (z[3] < 3528214618953670924 || (z[3] == 3528214618953670924 && (z[2] < 14536823245358974728 || (z[2] == 14536823245358974728 && (z[1] < 6387843321064356065 || (z[1] == 6387843321064356065 && (z[0] < 816069973256538473))))))))))))))))))) {
		var b uint64
		z[0], b = bits.Sub64(z[0], 816069973256538473, 0)
		z[1], b = bits.Sub64(z[1], 6387843321064356065, b)
		z[2], b = bits.Sub64(z[2], 14536823245358974728, b)
		z[3], b = bits.Sub64(z[3], 3528214618953670924, b)
		z[4], b = bits.Sub64(z[4], 7206257926599825404, b)
		z[5], b = bits.Sub64(z[5], 5159858282989125618, b)
		z[6], b = bits.Sub64(z[6], 4277310149175820203, b)
		z[7], b = bits.Sub64(z[7], 2252378430875190398, b)
		z[8], b = bits.Sub64(z[8], 2933629967605268401, b)
		z[9], _ = bits.Sub64(z[9], 64680000015521443, b)
	}
	if neg {
		//We have computed ( 2⁶³ r + X ) r⁻¹ = 2⁶³ + X r⁻¹ instead
		var b uint64
		z[0], b = bits.Sub64(z[0], signBitSelector, 0)
		z[1], b = bits.Sub64(z[1], 0, b)
		z[2], b = bits.Sub64(z[2], 0, b)
		z[3], b = bits.Sub64(z[3], 0, b)
		z[4], b = bits.Sub64(z[4], 0, b)
		z[5], b = bits.Sub64(z[5], 0, b)
		z[6], b = bits.Sub64(z[6], 0, b)
		z[7], b = bits.Sub64(z[7], 0, b)
		z[8], b = bits.Sub64(z[8], 0, b)
		z[9], b = bits.Sub64(z[9], 0, b)

		//Occurs iff x == 0 && xHi < 0, i.e. X = rX' for -2⁶³ ≤ X' < 0
		if b != 0 {
			// z[9] = -1
			//negative: add q
			const neg1 = 0xFFFFFFFFFFFFFFFF

			b = 0
			z[0], b = bits.Add64(z[0], 816069973256538473, b)
			z[1], b = bits.Add64(z[1], 6387843321064356065, b)
			z[2], b = bits.Add64(z[2], 14536823245358974728, b)
			z[3], b = bits.Add64(z[3], 3528214618953670924, b)
			z[4], b = bits.Add64(z[4], 7206257926599825404, b)
			z[5], b = bits.Add64(z[5], 5159858282989125618, b)
			z[6], b = bits.Add64(z[6], 4277310149175820203, b)
			z[7], b = bits.Add64(z[7], 2252378430875190398, b)
			z[8], b = bits.Add64(z[8], 2933629967605268401, b)
			z[9], _ = bits.Add64(neg1, 64680000015521443, b)
		}
	}
}

// mulWSigned mul word signed (w/ montgomery reduction)
func (z *e_nocarry_0632) mulWSigned(x *e_nocarry_0632, y int64) {
	m := y >> 63
	_mulWGeneric(z, x, uint64((y^m)-m))
	//multiply by abs(y)
	if y < 0 {
		z.Neg(z)
	}
}

// regular multiplication by one word regular (non montgomery)
// Fewer additions than the branch-free for positive y. Could be faster on some architectures
func (z *e_nocarry_0632) mulWRegularBr(x *e_nocarry_0632, y int64) uint64 {

	// w := abs(y)
	m := y >> 63
	w := uint64((y ^ m) - m)

	var c uint64
	c, z[0] = bits.Mul64(x[0], w)
	c, z[1] = madd1(x[1], w, c)
	c, z[2] = madd1(x[2], w, c)
	c, z[3] = madd1(x[3], w, c)
	c, z[4] = madd1(x[4], w, c)
	c, z[5] = madd1(x[5], w, c)
	c, z[6] = madd1(x[6], w, c)
	c, z[7] = madd1(x[7], w, c)
	c, z[8] = madd1(x[8], w, c)
	c, z[9] = madd1(x[9], w, c)

	if y < 0 {
		c = z.neg(z, c)
	}

	return c
}

func (z *e_nocarry_0632) neg(x *e_nocarry_0632, xHi uint64) uint64 {
	b := uint64(0)

	z[0], b = bits.Sub64(0, x[0], 0)
	z[1], b = bits.Sub64(0, x[1], b)
	z[2], b = bits.Sub64(0, x[2], b)
	z[3], b = bits.Sub64(0, x[3], b)
	z[4], b = bits.Sub64(0, x[4], b)
	z[5], b = bits.Sub64(0, x[5], b)
	z[6], b = bits.Sub64(0, x[6], b)
	z[7], b = bits.Sub64(0, x[7], b)
	z[8], b = bits.Sub64(0, x[8], b)
	z[9], b = bits.Sub64(0, x[9], b)
	xHi, _ = bits.Sub64(0, xHi, b)

	return xHi
}

// mulWRegular branch-free regular multiplication by one word (non montgomery)
func (z *e_nocarry_0632) mulWRegular(x *e_nocarry_0632, y int64) uint64 {

	w := uint64(y)
	allNeg := uint64(y >> 63) // -1 if y < 0, 0 o.w

	//s[0], s[1] so results are not stored immediately in z.
	//x[i] will be needed in the i+1 th iteration. We don't want to overwrite it in case x = z
	var s [2]uint64
	var h [2]uint64

	h[0], s[0] = bits.Mul64(x[0], w)

	c := uint64(0)
	b := uint64(0)

	{
		const curI = 1 % 2
		const prevI = 1 - curI
		const iMinusOne = 1 - 1

		h[curI], s[curI] = bits.Mul64(x[1], w)
		s[curI], c = bits.Add64(s[curI], h[prevI], c)
		s[curI], b = bits.Sub64(s[curI], allNeg&x[iMinusOne], b)
		z[iMinusOne] = s[prevI]
	}

	{
		const curI = 2 % 2
		const prevI = 1 - curI
		const iMinusOne = 2 - 1

		h[curI], s[curI] = bits.Mul64(x[2], w)
		s[curI], c = bits.Add64(s[curI], h[prevI], c)
		s[curI], b = bits.Sub64(s[curI], allNeg&x[iMinusOne], b)
		z[iMinusOne] = s[prevI]
	}

	{
		const curI = 3 % 2
		const prevI = 1 - curI
		const iMinusOne = 3 - 1

		h[curI], s[curI] = bits.Mul64(x[3], w)
		s[curI], c = bits.Add64(s[curI], h[prevI], c)
		s[curI], b = bits.Sub64(s[curI], allNeg&x[iMinusOne], b)
		z[iMinusOne] = s[prevI]
	}

	{
		const curI = 4 % 2
		const prevI = 1 - curI
		const iMinusOne = 4 - 1

		h[curI], s[curI] = bits.Mul64(x[4], w)
		s[curI], c = bits.Add64(s[curI], h[prevI], c)
		s[curI], b = bits.Sub64(s[curI], allNeg&x[iMinusOne], b)
		z[iMinusOne] = s[prevI]
	}

	{
		const curI = 5 % 2
		const prevI = 1 - curI
		const iMinusOne = 5 - 1

		h[curI], s[curI] = bits.Mul64(x[5], w)
		s[curI], c = bits.Add64(s[curI], h[prevI], c)
		s[curI], b = bits.Sub64(s[curI], allNeg&x[iMinusOne], b)
		z[iMinusOne] = s[prevI]
	}

	{
		const curI = 6 % 2
		const prevI = 1 - curI
		const iMinusOne = 6 - 1

		h[curI], s[curI] = bits.Mul64(x[6], w)
		s[curI], c = bits.Add64(s[curI], h[prevI], c)
		s[curI], b = bits.Sub64(s[curI], allNeg&x[iMinusOne], b)
		z[iMinusOne] = s[prevI]
	}

	{
		const curI = 7 % 2
		const prevI = 1 - curI
		const iMinusOne = 7 - 1

		h[curI], s[curI] = bits.Mul64(x[7], w)
		s[curI], c = bits.Add64(s[curI], h[prevI], c)
		s[curI], b = bits.Sub64(s[curI], allNeg&x[iMinusOne], b)
		z[iMinusOne] = s[prevI]
	}

	{
		const curI = 8 % 2
		const prevI = 1 - curI
		const iMinusOne = 8 - 1

		h[curI], s[curI] = bits.Mul64(x[8], w)
		s[curI], c = bits.Add64(s[curI], h[prevI], c)
		s[curI], b = bits.Sub64(s[curI], allNeg&x[iMinusOne], b)
		z[iMinusOne] = s[prevI]
	}

	{
		const curI = 9 % 2
		const prevI = 1 - curI
		const iMinusOne = 9 - 1

		h[curI], s[curI] = bits.Mul64(x[9], w)
		s[curI], c = bits.Add64(s[curI], h[prevI], c)
		s[curI], b = bits.Sub64(s[curI], allNeg&x[iMinusOne], b)
		z[iMinusOne] = s[prevI]
	}
	{
		const curI = 10 % 2
		const prevI = 1 - curI
		const iMinusOne = 9

		s[curI], _ = bits.Sub64(h[prevI], allNeg&x[iMinusOne], b)
		z[iMinusOne] = s[prevI]

		return s[curI] + c
	}
}

//Requires NoCarry
func (z *e_nocarry_0632) linearCombNonModular(x *e_nocarry_0632, xC int64, y *e_nocarry_0632, yC int64) uint64 {
	var yTimes e_nocarry_0632

	yHi := yTimes.mulWRegular(y, yC)
	xHi := z.mulWRegular(x, xC)

	carry := uint64(0)
	z[0], carry = bits.Add64(z[0], yTimes[0], carry)
	z[1], carry = bits.Add64(z[1], yTimes[1], carry)
	z[2], carry = bits.Add64(z[2], yTimes[2], carry)
	z[3], carry = bits.Add64(z[3], yTimes[3], carry)
	z[4], carry = bits.Add64(z[4], yTimes[4], carry)
	z[5], carry = bits.Add64(z[5], yTimes[5], carry)
	z[6], carry = bits.Add64(z[6], yTimes[6], carry)
	z[7], carry = bits.Add64(z[7], yTimes[7], carry)
	z[8], carry = bits.Add64(z[8], yTimes[8], carry)
	z[9], carry = bits.Add64(z[9], yTimes[9], carry)

	yHi, _ = bits.Add64(xHi, yHi, carry)

	return yHi
}
