// Copyright 2020-2025 Consensys Software Inc.
// Licensed under the Apache License, Version 2.0. See the LICENSE file for details.

// Code generated by consensys/gnark-crypto DO NOT EDIT

// Package extensions implements the fields arithmetic of the 𝔽r² and 𝔽r⁴
// extensions of the koalabear field.
//
//   - For extension 4:
//     𝔽r²[u] = 𝔽r/u²-3
//     𝔽r⁴[v] = 𝔽r²/v²-u
//
//   - For extension 6:
//     𝔽r⁶[w] = 𝔽r²/w³-u-1
//
// or equivalently:
//
//	𝔽r⁶[w] = 𝔽r/w⁶-2w³-2
package extensions
