// +build !purego

// Code generated by gnark-crypto/generator. DO NOT EDIT.
// We include the hash to force the Go compiler to recompile: 11526023363388295562
#include "../../../field/asm/element_5w_amd64.s"

