// +build !purego

// Code generated by gnark-crypto/generator. DO NOT EDIT.
// We include the hash to force the Go compiler to recompile: 8407829078885064293
#include "../../../field/asm/element_12w_amd64.s"

